// client/src/lib/components/editor/MomentEditForm.svelte
<script lang="ts">
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import { ICONS } from '$lib/utils/icons';
	import type { Moment } from '$lib/types/api';

	interface SavePatch {
		name: string;
		description: string;
		startSeconds: number;
		endSeconds: number;
	}

	interface Props {
		moment: Moment | null;
		duration: number;
		downloadPending?: boolean;
		onsave?: (patch: SavePatch) => void;
		onsetToPlayhead?: (field: 'start' | 'end') => void;
		ondelete?: (momentId: string) => void;
		onclose?: () => void;
		onexport?: (momentId: string) => void;
		ondownload?: (momentId: string) => void;
		onshare?: (momentId: string) => void;
	}

	let {
		moment,
		duration,
		downloadPending = false,
		onsave,
		onsetToPlayhead,
		ondelete,
		onclose,
		onexport,
		ondownload,
		onshare
	}: Props = $props();

	let name = $state('');
	let description = $state('');
	let startSeconds = $state<number | string>(0);
	let endSeconds = $state<number | string>(0);

	// Repopulate the editable fields whenever a (different) moment is loaded —
	// mirrors the Vue `watch(() => props.moment, …, { immediate: true })`. Keyed on
	// `moment?.id` so user edits aren't clobbered on unrelated reactive churn.
	let lastId: string | null = null;
	$effect(() => {
		const m = moment;
		if (!m) return;
		if (m.id === lastId) return;
		lastId = m.id;
		name = m.name;
		description = m.description;
		startSeconds = m.startSeconds;
		endSeconds = m.endSeconds;
	});

	function onSave() {
		if (!moment) return;
		const start = Math.max(0, Number(startSeconds) || 0);
		const end = Math.max(start + 0.001, Number(endSeconds) || 0);
		onsave?.({ name, description, startSeconds: start, endSeconds: end });
	}

	function onDelete() {
		if (!moment) return;
		ondelete?.(moment.id);
	}

	const reprocessDisabled = $derived(
		moment?.exportStatus === 'queued' || moment?.exportStatus === 'processing'
	);
</script>

{#if moment}
	<div class="flex flex-col card preset-outlined-surface-200-800 bg-surface-50-950">
		<!-- Header -->
		<div class="flex items-center justify-between gap-2 border-b border-surface-200-800 p-3">
			<p class="text-sm font-semibold">Edit moment</p>
			<div class="flex items-center gap-1">
				<Button
					variant="tonal"
					color="primary"
					size="sm"
					disabled={reprocessDisabled}
					title="Reprocess"
					onclick={() => onexport?.(moment.id)}
				>
					{#snippet icon()}
						<AppIcon name={ICONS.reload} class="size-4" />
					{/snippet}
					Reprocess
				</Button>

				<Button
					iconOnly
					size="sm"
					variant="tonal"
					color="surface"
					title="Download"
					loading={downloadPending}
					onclick={() => ondownload?.(moment.id)}
				>
					{#snippet icon()}
						<AppIcon name={ICONS.download} class="size-4" />
					{/snippet}
				</Button>

				<Button
					iconOnly
					size="sm"
					variant="tonal"
					color="surface"
					title="Share"
					onclick={() => onshare?.(moment.id)}
				>
					{#snippet icon()}
						<AppIcon name={ICONS.share} class="size-4" />
					{/snippet}
				</Button>

				<Button
					iconOnly
					size="sm"
					variant="tonal"
					color="surface"
					aria-label="Close"
					title="Close"
					onclick={() => onclose?.()}
				>
					{#snippet icon()}
						<AppIcon name={ICONS.close} class="size-4" />
					{/snippet}
				</Button>
			</div>
		</div>

		<!-- Body -->
		<div class="flex flex-col gap-2 p-3">
			<div class="flex items-center gap-2">
				<label class="w-24 shrink-0 text-xs font-medium text-surface-600-400" for="moment-name">
					Name
				</label>
				<input
					id="moment-name"
					class="input min-w-0 flex-1"
					placeholder="Untitled"
					bind:value={name}
				/>
			</div>

			<div class="flex gap-2">
				<label
					class="w-24 shrink-0 self-start pt-1.5 text-xs font-medium text-surface-600-400"
					for="moment-description"
				>
					Description
				</label>
				<textarea
					id="moment-description"
					class="textarea min-w-0 flex-1"
					placeholder="Notes"
					rows="2"
					bind:value={description}
				></textarea>
			</div>

			<div class="flex flex-wrap gap-2">
				<div class="flex min-w-[220px] flex-1 items-center gap-2">
					<label class="w-24 shrink-0 text-xs font-medium text-surface-600-400" for="moment-start">
						Start
					</label>
					<input
						id="moment-start"
						class="input min-w-0 flex-1"
						type="number"
						step="0.01"
						min="0"
						max={duration}
						bind:value={startSeconds}
					/>
					<Button
						iconOnly
						size="sm"
						variant="tonal"
						color="primary"
						title="Set to playhead"
						onclick={() => onsetToPlayhead?.('start')}
					>
						{#snippet icon()}
							<AppIcon name={ICONS.snapToPlayhead} class="size-4" />
						{/snippet}
					</Button>
				</div>

				<div class="flex min-w-[220px] flex-1 items-center gap-2">
					<label class="w-24 shrink-0 text-xs font-medium text-surface-600-400" for="moment-end">
						End
					</label>
					<input
						id="moment-end"
						class="input min-w-0 flex-1"
						type="number"
						step="0.01"
						min="0"
						max={duration}
						bind:value={endSeconds}
					/>
					<Button
						iconOnly
						size="sm"
						variant="tonal"
						color="primary"
						title="Set to playhead"
						onclick={() => onsetToPlayhead?.('end')}
					>
						{#snippet icon()}
							<AppIcon name={ICONS.snapToPlayhead} class="size-4" />
						{/snippet}
					</Button>
				</div>
			</div>
		</div>

		<!-- Footer -->
		<div class="flex w-full items-center justify-end gap-2 border-t border-surface-200-800 p-3">
			<Button variant="tonal" color="error" size="sm" onclick={onDelete}>
				{#snippet icon()}
					<AppIcon name={ICONS.trash} class="size-4" />
				{/snippet}
				Delete
			</Button>
			<Button size="sm" onclick={onSave}>
				{#snippet icon()}
					<AppIcon name={ICONS.save} class="size-4" />
				{/snippet}
				Save
			</Button>
		</div>
	</div>
{/if}

// frontend/app/components/editor/MomentEditForm.vue
<script setup lang="ts">
import { ICONS } from "~/utils/icons";
import { ref, watch } from "vue";
import type { Moment } from "~~/shared/types/api";

const props = defineProps<{
  moment: Moment | null;
  currentTime: number;
  duration: number;
  downloadPending?: boolean;
}>();

const emit = defineEmits<{
  save: [patch: { name: string; description: string; startSeconds: number; endSeconds: number }];
  "set-to-playhead": [field: "start" | "end"];
  delete: [momentId: string];
  close: [];
  export: [momentId: string];
  download: [momentId: string];
  share: [momentId: string];
}>();

const name = ref("");
const description = ref("");
const startSeconds = ref(0);
const endSeconds = ref(0);

watch(
  () => props.moment,
  (m) => {
    if (!m) return;
    name.value = m.name;
    description.value = m.description;
    startSeconds.value = m.startSeconds;
    endSeconds.value = m.endSeconds;
  },
  { immediate: true },
);

function onSave() {
  if (!props.moment) return;
  const start = Math.max(0, Number(startSeconds.value) || 0);
  const end = Math.max(start + 0.001, Number(endSeconds.value) || 0);
  emit("save", {
    name: name.value,
    description: description.value,
    startSeconds: start,
    endSeconds: end,
  });
}

function onDelete() {
  if (!props.moment) return;
  emit("delete", props.moment.id);
}
</script>

<template>
  <UCard v-if="moment" :ui="{ body: 'p-3 sm:p-3', header: 'p-3 sm:p-3', footer: 'p-3 sm:p-3' }">
    <template #header>
      <div class="flex items-center justify-between gap-2">
        <p class="text-sm font-semibold">Edit moment</p>
        <div class="flex items-center gap-1">
          <UTooltip text="Reprocess">
            <UButton
              color="primary"
              variant="soft"
              size="xs"
              :icon="ICONS.reload"
              :disabled="moment.exportStatus === 'queued' || moment.exportStatus === 'processing'"
              @click="emit('export', moment.id)"
            >
              Reprocess
            </UButton>
          </UTooltip>
          <UTooltip text="Download">
            <UButton
              color="neutral"
              variant="ghost"
              size="xs"
              :icon="ICONS.download"
              square
              :loading="downloadPending"
              @click="emit('download', moment.id)"
            />
          </UTooltip>
          <UTooltip text="Share">
            <UButton
              color="neutral"
              variant="ghost"
              size="xs"
              :icon="ICONS.share"
              square
              @click="emit('share', moment.id)"
            />
          </UTooltip>
          <UButton
            color="neutral"
            variant="ghost"
            size="xs"
            :icon="ICONS.close"
            square
            aria-label="Close"
            @click="emit('close')"
          />
        </div>
      </div>
    </template>

    <div class="flex flex-col gap-2">
      <div class="flex items-center gap-2">
        <label class="text-xs font-medium text-muted w-24 shrink-0">Name</label>
        <UInput v-model="name" size="xs" placeholder="Untitled" :ui="{ root: 'flex-1 min-w-0' }" />
      </div>

      <div class="flex gap-2">
        <label class="text-xs font-medium text-muted w-24 shrink-0 self-start pt-1.5">
          Description
        </label>
        <UTextarea
          v-model="description"
          size="xs"
          placeholder="Notes"
          :rows="2"
          class="flex-1 min-w-0"
        />
      </div>

      <div class="flex flex-wrap gap-x-2 gap-y-2">
        <div class="flex items-center gap-2 flex-1 min-w-[220px]">
          <label class="text-xs font-medium text-muted w-24 shrink-0">Start</label>
          <UInput
            v-model="startSeconds"
            size="xs"
            type="number"
            step="0.01"
            min="0"
            :max="duration"
            :ui="{ root: 'flex-1 min-w-0' }"
          />
          <UTooltip text="Set to playhead">
            <UButton
              color="primary"
              variant="ghost"
              size="xs"
              :icon="ICONS.snapToPlayhead"
              square
              @click="emit('set-to-playhead', 'start')"
            />
          </UTooltip>
        </div>

        <div class="flex items-center gap-2 flex-1 min-w-[220px]">
          <label class="text-xs font-medium text-muted w-24 shrink-0">End</label>
          <UInput
            v-model="endSeconds"
            size="xs"
            type="number"
            step="0.01"
            min="0"
            :max="duration"
            :ui="{ root: 'flex-1 min-w-0' }"
          />
          <UTooltip text="Set to playhead">
            <UButton
              color="primary"
              variant="ghost"
              size="xs"
              :icon="ICONS.snapToPlayhead"
              square
              @click="emit('set-to-playhead', 'end')"
            />
          </UTooltip>
        </div>
      </div>
    </div>

    <template #footer>
      <div class="flex items-center justify-end gap-2 w-full">
        <UButton color="error" variant="soft" size="xs" :icon="ICONS.trash" @click="onDelete">
          Delete
        </UButton>
        <UButton color="primary" size="xs" :icon="ICONS.save" @click="onSave"> Save </UButton>
      </div>
    </template>
  </UCard>
</template>
