// frontend/app/components/library/settings/LibraryMemberRow.vue
<script setup lang="ts">
import type { LibraryMemberWithUser } from "~~/shared/types/api";
import AppIcon from "~/components/AppIcon.vue";
import UserAvatar from "~/components/UserAvatar.vue";

interface RoleOption {
  label: string;
  value: "admin" | "viewer";
}

interface Props {
  member: LibraryMemberWithUser;
  roleDraft: "admin" | "viewer";
  updatingRole: boolean;
  removing: boolean;
  roleOptions: RoleOption[];
}

defineProps<Props>();

const emit = defineEmits<{
  updateRole: [member: LibraryMemberWithUser, role: "admin" | "viewer"];
  remove: [member: LibraryMemberWithUser];
}>();
</script>

<template>
  <div class="px-3 py-3 flex flex-col md:flex-row md:items-center gap-3">
    <div class="flex items-center gap-3 flex-1 min-w-0">
      <UserAvatar
        :display-name="member.user.displayName"
        :avatar-url="member.user.avatarUrl"
        size-class="w-8"
      />
      <div class="min-w-0">
        <p class="text-sm font-medium truncate">{{ member.user.displayName }}</p>
        <p class="text-xs text-muted truncate">{{ member.user.email }}</p>
      </div>
    </div>

    <div class="flex items-center gap-2">
      <span v-if="member.role === 'owner'" class="badge badge-sm badge-primary">owner</span>
      <template v-else>
        <select
          :value="roleDraft"
          class="select w-28"
          :disabled="updatingRole"
          @change="
            emit(
              'updateRole',
              member,
              ($event.target as HTMLSelectElement).value as 'admin' | 'viewer',
            )
          "
        >
          <option v-for="item in roleOptions" :key="item.value" :value="item.value">
            {{ item.label }}
          </option>
        </select>
        <button
          class="btn btn-sm btn-error btn-soft"
          :disabled="removing"
          @click="emit('remove', member)"
        >
          <span v-if="removing" class="loading loading-spinner loading-xs"></span>
          <AppIcon v-else name="i-lucide-user-minus" class="size-4" />
        </button>
      </template>
    </div>
  </div>
</template>

// client/src/lib/components/library/settings/LibraryMemberRow.svelte
<script lang="ts">
	import { ICONS } from '$lib/utils/icons';
	import type { LibraryMemberWithUser } from '$lib/types/api';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import UserAvatar from '$lib/components/ui/UserAvatar.svelte';

	interface RoleOption {
		label: string;
		value: 'admin' | 'viewer';
	}

	interface Props {
		member: LibraryMemberWithUser;
		roleDraft: 'admin' | 'viewer';
		updatingRole: boolean;
		removing: boolean;
		roleOptions: RoleOption[];
		onupdateRole?: (member: LibraryMemberWithUser, role: 'admin' | 'viewer') => void;
		onremove?: (member: LibraryMemberWithUser) => void;
	}

	let { member, roleDraft, updatingRole, removing, roleOptions, onupdateRole, onremove }: Props =
		$props();
</script>

<div class="flex flex-col gap-3 px-3 py-3 md:flex-row md:items-center">
	<div class="flex min-w-0 flex-1 items-center gap-3">
		<UserAvatar
			displayName={member.user.displayName}
			avatarUrl={member.user.avatarUrl}
			sizeClass="w-8"
		/>
		<div class="min-w-0">
			<p class="truncate text-sm font-medium">{member.user.displayName}</p>
			<p class="truncate text-xs text-surface-600-400">{member.user.email}</p>
		</div>
	</div>

	<div class="flex items-center gap-2">
		{#if member.role === 'owner'}
			<span class="badge preset-tonal-primary">owner</span>
		{:else}
			<select
				class="select w-28"
				value={roleDraft}
				disabled={updatingRole}
				onchange={(e) => onupdateRole?.(member, e.currentTarget.value as 'admin' | 'viewer')}
			>
				{#each roleOptions as option (option.value)}
					<option value={option.value}>{option.label}</option>
				{/each}
			</select>
			<button
				type="button"
				class="btn-icon btn-icon-sm preset-tonal-error"
				aria-label="Remove member"
				title="Remove member"
				disabled={removing}
				onclick={() => onremove?.(member)}
			>
				{#if removing}
					<AppIcon name={ICONS.loading} class="size-4 animate-spin" />
				{:else}
					<AppIcon name={ICONS.user} class="size-4" />
				{/if}
			</button>
		{/if}
	</div>
</div>
