// frontend/app/components/library/LibraryEntryCard.vue
<script setup lang="ts">
import { ICONS } from "~/utils/icons";
import { computed } from "vue";
import type { LibraryEntry, LibraryFile } from "~~/shared/types/api";
import { apiUrl } from "~/utils/api-fetch";
import { formatDuration } from "~/utils/format-duration";
import { getMimeIcon } from "~/utils/mime-icons";
import AppIcon from "~/components/AppIcon.vue";
import AlcovesImage from "~/components/AlcovesImage.vue";

interface Props {
  entry: LibraryEntry;
  libraryId: string;
  showTrashed: boolean;
  dragEnabled: boolean;
  draggedFileIds: string[];
  dropTargetFolderId: string | null;
  renameValue: string;
  isEntrySelected: (entry: LibraryEntry) => boolean;
  isRenaming: (entry: LibraryEntry) => boolean;
  failedThumbnails: Set<string>;
  isImageFile: (file: LibraryFile) => boolean;
  isSmallImage: (file: LibraryFile) => boolean;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  rowClick: [entry: LibraryEntry, event: MouseEvent];
  rowDoubleClick: [entry: LibraryEntry];
  rowContextMenu: [entry: LibraryEntry, event: MouseEvent];
  dragStart: [entry: LibraryEntry, event: DragEvent];
  dragEnd: [];
  dragEnter: [entry: LibraryEntry];
  dragOver: [entry: LibraryEntry, event: DragEvent];
  dragLeave: [entry: LibraryEntry, event: DragEvent];
  drop: [entry: LibraryEntry, event: DragEvent];
  saveRename: [entry: LibraryEntry];
  cancelRename: [];
  updateRenameValue: [value: string];
  thumbnailError: [fileId: string];
}>();

// YouTube-style duration overlay, shown only for video files that carry a
// known duration. null hides the badge (missing/zero-length/still-processing).
const durationLabel = computed(() =>
  props.entry.kind === "file" && props.entry.mimeType.startsWith("video/")
    ? formatDuration(props.entry.duration)
    : null,
);
</script>

<template>
  <div
    class="rounded-md overflow-hidden cursor-pointer transition-colors select-none"
    :class="[
      props.isEntrySelected(props.entry)
        ? 'bg-primary/20 hover:bg-primary/28'
        : 'bg-elevated hover:bg-primary/10',
      props.dropTargetFolderId === props.entry.id && props.entry.kind === 'folder'
        ? 'ring-2 ring-primary/60 bg-primary/10'
        : '',
      props.draggedFileIds.includes(props.entry.id) && props.entry.kind === 'file'
        ? 'opacity-60'
        : '',
    ]"
    :draggable="props.dragEnabled && props.entry.kind === 'file' && !props.isRenaming(props.entry)"
    @click="emit('rowClick', props.entry, $event)"
    @dblclick="emit('rowDoubleClick', props.entry)"
    @contextmenu="emit('rowContextMenu', props.entry, $event)"
    @dragstart="emit('dragStart', props.entry, $event)"
    @dragend="emit('dragEnd')"
    @dragenter="emit('dragEnter', props.entry)"
    @dragover="emit('dragOver', props.entry, $event)"
    @dragleave="emit('dragLeave', props.entry, $event)"
    @drop="emit('drop', props.entry, $event)"
  >
    <div
      v-if="props.isRenaming(props.entry)"
      :data-rename-input-entry-id="props.entry.id"
      class="px-2 pt-2 pb-2"
    >
      <UInput
        :model-value="renameValue"
        size="sm"
        autofocus
        :ui="{ root: 'w-full' }"
        @update:model-value="emit('updateRenameValue', String($event ?? ''))"
        @blur="emit('saveRename', props.entry)"
        @keydown.enter="emit('saveRename', props.entry)"
        @keydown.escape="emit('cancelRename')"
        @click.stop
      />
    </div>

    <div
      v-else
      class="px-2 flex items-start gap-2 min-w-0"
      :class="props.entry.kind === 'folder' ? 'py-3' : 'pt-2 pb-2'"
    >
      <AppIcon
        :name="props.entry.kind === 'folder' ? ICONS.folder : getMimeIcon(props.entry.mimeType)"
        class="size-4 mt-0.5 shrink-0 text-muted"
        :class="showTrashed && props.entry.kind === 'file' ? 'opacity-50' : ''"
      />
      <span
        v-if="props.entry.kind === 'folder'"
        class="text-sm font-semibold text-left truncate w-full"
        :title="
          showTrashed
            ? `${props.entry.name} (${props.entry.trashFileCount ?? 0} files)`
            : props.entry.name
        "
      >
        {{
          showTrashed
            ? `${props.entry.name} (${props.entry.trashFileCount ?? 0} files)`
            : props.entry.name
        }}
      </span>
      <span
        v-else
        class="text-sm font-semibold text-left truncate w-full"
        :title="props.entry.name"
      >
        {{ props.entry.name }}
      </span>
      <UTooltip
        v-if="props.entry.kind === 'file' && props.entry.hasDuplicates"
        text="Duplicate of another file in this library"
      >
        <UIcon :name="ICONS.duplicate" class="size-4 mt-0.5 shrink-0 text-warning" />
      </UTooltip>
      <div v-if="props.entry.tags?.length" class="flex items-center gap-1 shrink-0">
        <span
          v-for="tag in props.entry.tags"
          :key="tag.id"
          class="size-2 rounded-full border border-default/50"
          :title="tag.name"
          :style="{ backgroundColor: tag.color }"
        />
      </div>
    </div>

    <div
      v-if="props.entry.kind === 'file'"
      class="aspect-video w-full bg-default flex items-center justify-center overflow-hidden"
    >
      <template v-if="props.entry.mimeType.startsWith('video/')">
        <div class="relative w-full h-full flex items-center justify-center">
          <AlcovesImage
            v-if="!props.failedThumbnails.has(props.entry.id) && props.entry.thumbnailFileId"
            :library-id="libraryId"
            :file-id="props.entry.thumbnailFileId"
            :alt="props.entry.name"
            variant="card"
            :source-width="props.entry.width"
            :source-height="props.entry.height"
            class="w-full h-full object-cover"
            @error="emit('thumbnailError', props.entry.id)"
          />
          <img
            v-else-if="!props.failedThumbnails.has(props.entry.id)"
            :src="apiUrl(`/api/libraries/${libraryId}/files/${props.entry.id}/thumbnail`)"
            :alt="props.entry.name"
            class="w-full h-full object-cover"
            loading="lazy"
            decoding="async"
            draggable="false"
            crossorigin="use-credentials"
            @error="emit('thumbnailError', props.entry.id)"
          />
          <AppIcon v-else :name="ICONS.movie" class="size-10 text-muted" />
          <div
            v-if="props.entry.proxyStatus === 'processing'"
            class="absolute inset-0 flex items-center justify-center bg-black/40"
          >
            <UIcon :name="ICONS.loading" class="size-5 animate-spin text-white" />
          </div>
          <span
            v-if="durationLabel"
            class="absolute bottom-1 right-1 rounded bg-black/80 px-1.5 py-0.5 text-xs font-medium leading-none tabular-nums text-white"
          >
            {{ durationLabel }}
          </span>
        </div>
      </template>
      <template v-else-if="props.entry.kind === 'file' && props.isImageFile(props.entry)">
        <AlcovesImage
          v-if="!props.failedThumbnails.has(props.entry.id)"
          :library-id="libraryId"
          :file-id="props.entry.id"
          :alt="props.entry.name"
          variant="card"
          :source-width="props.entry.width"
          :source-height="props.entry.height"
          :class="props.isSmallImage(props.entry) ? 'object-contain' : 'w-full h-full object-cover'"
          @error="emit('thumbnailError', props.entry.id)"
        />
        <AppIcon v-else :name="ICONS.image" class="size-10 text-muted" />
      </template>
      <template v-else-if="props.entry.kind === 'file'">
        <AppIcon
          :name="getMimeIcon(props.entry.mimeType)"
          class="size-10 text-muted"
          :class="showTrashed ? 'opacity-50' : ''"
        />
      </template>
    </div>
  </div>
</template>

// client/src/lib/components/library/LibraryEntryCard.svelte
<script lang="ts">
	import { ICONS } from '$lib/utils/icons';
	import type { LibraryEntry, LibraryFile } from '$lib/types/api';
	import { apiUrl } from '$lib/api';
	import { formatDuration } from '$lib/utils/format-duration';
	import { getMimeIcon } from '$lib/utils/mime-icons';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import AlcovesImage from '$lib/components/ui/AlcovesImage.svelte';

	interface Props {
		entry: LibraryEntry;
		libraryId: string;
		showTrashed: boolean;
		dragEnabled: boolean;
		draggedFileIds: string[];
		dropTargetFolderId: string | null;
		renameValue: string;
		isEntrySelected: (entry: LibraryEntry) => boolean;
		isRenaming: (entry: LibraryEntry) => boolean;
		failedThumbnails: Set<string>;
		isImageFile: (file: LibraryFile) => boolean;
		isSmallImage: (file: LibraryFile) => boolean;
		onrowClick?: (entry: LibraryEntry, event: MouseEvent) => void;
		onrowDoubleClick?: (entry: LibraryEntry) => void;
		onrowContextMenu?: (entry: LibraryEntry, event: MouseEvent) => void;
		ondragStart?: (entry: LibraryEntry, event: DragEvent) => void;
		ondragEnd?: () => void;
		ondragEnter?: (entry: LibraryEntry) => void;
		ondragOver?: (entry: LibraryEntry, event: DragEvent) => void;
		ondragLeave?: (entry: LibraryEntry, event: DragEvent) => void;
		ondrop?: (entry: LibraryEntry, event: DragEvent) => void;
		onsaveRename?: (entry: LibraryEntry) => void;
		oncancelRename?: () => void;
		onupdateRenameValue?: (value: string) => void;
		onthumbnailError?: (fileId: string) => void;
	}

	let {
		entry,
		libraryId,
		showTrashed,
		dragEnabled,
		draggedFileIds,
		dropTargetFolderId,
		renameValue,
		isEntrySelected,
		isRenaming,
		failedThumbnails,
		isImageFile,
		isSmallImage,
		onrowClick,
		onrowDoubleClick,
		onrowContextMenu,
		ondragStart,
		ondragEnd,
		ondragEnter,
		ondragOver,
		ondragLeave,
		ondrop,
		onsaveRename,
		oncancelRename,
		onupdateRenameValue,
		onthumbnailError
	}: Props = $props();

	// YouTube-style duration overlay, shown only for video files that carry a
	// known duration. null hides the badge (missing/zero-length/still-processing).
	const durationLabel = $derived(
		entry.kind === 'file' && entry.mimeType.startsWith('video/')
			? formatDuration(entry.duration)
			: null
	);

	const selected = $derived(isEntrySelected(entry));
	const renaming = $derived(isRenaming(entry));
	const isDropTarget = $derived(dropTargetFolderId === entry.id && entry.kind === 'folder');
	const isDragging = $derived(draggedFileIds.includes(entry.id) && entry.kind === 'file');

	const folderTitle = $derived(
		entry.kind === 'folder' && showTrashed
			? `${entry.name} (${entry.trashFileCount ?? 0} files)`
			: entry.name
	);
</script>

<div
	role="button"
	tabindex="0"
	class={[
		'cursor-pointer overflow-hidden rounded-md transition-colors select-none',
		selected
			? 'bg-primary-500/20 hover:bg-primary-500/30'
			: 'bg-surface-100-900 hover:bg-primary-500/10',
		isDropTarget ? 'bg-primary-500/10 ring-2 ring-primary-500' : '',
		isDragging ? 'opacity-60' : ''
	]}
	draggable={dragEnabled && entry.kind === 'file' && !renaming}
	onclick={(e) => onrowClick?.(entry, e)}
	onkeydown={(e) => {
		if (!renaming && (e.key === 'Enter' || e.key === ' ')) {
			e.preventDefault();
			onrowClick?.(entry, e as unknown as MouseEvent);
		}
	}}
	ondblclick={() => onrowDoubleClick?.(entry)}
	oncontextmenu={(e) => onrowContextMenu?.(entry, e)}
	ondragstart={(e) => ondragStart?.(entry, e)}
	ondragend={() => ondragEnd?.()}
	ondragenter={() => ondragEnter?.(entry)}
	ondragover={(e) => ondragOver?.(entry, e)}
	ondragleave={(e) => ondragLeave?.(entry, e)}
	ondrop={(e) => ondrop?.(entry, e)}
>
	{#if renaming}
		<div data-rename-input-entry-id={entry.id} class="px-2 pt-2 pb-2">
			<!-- svelte-ignore a11y_autofocus -->
			<input
				class="input"
				value={renameValue}
				autofocus
				oninput={(e) => onupdateRenameValue?.((e.currentTarget as HTMLInputElement).value)}
				onblur={() => onsaveRename?.(entry)}
				onkeydown={(e) => {
					if (e.key === 'Enter') onsaveRename?.(entry);
					else if (e.key === 'Escape') oncancelRename?.();
				}}
				onclick={(e) => e.stopPropagation()}
			/>
		</div>
	{:else}
		<div
			class="flex min-w-0 items-start gap-2 px-2"
			class:py-3={entry.kind === 'folder'}
			class:pt-2={entry.kind !== 'folder'}
			class:pb-2={entry.kind !== 'folder'}
		>
			<AppIcon
				name={entry.kind === 'folder' ? ICONS.folder : getMimeIcon(entry.mimeType)}
				class={[
					'mt-0.5 size-4 shrink-0 text-surface-500',
					showTrashed && entry.kind === 'file' ? 'opacity-50' : ''
				].join(' ')}
			/>
			<span class="w-full truncate text-left text-sm font-semibold" title={folderTitle}>
				{folderTitle}
			</span>
			{#if entry.kind === 'file' && entry.hasDuplicates}
				<span class="mt-0.5 shrink-0" title="Duplicate of another file in this library">
					<AppIcon name={ICONS.duplicate} class="size-4 text-warning-500" />
				</span>
			{/if}
			{#if entry.tags?.length}
				<div class="flex shrink-0 items-center gap-1">
					{#each entry.tags as tag (tag.id)}
						<span
							class="size-2 rounded-full border border-surface-400/50"
							title={tag.name}
							style:background-color={tag.color}
						></span>
					{/each}
				</div>
			{/if}
		</div>

		{#if entry.kind === 'file'}
			<div
				class="flex aspect-video w-full items-center justify-center overflow-hidden bg-surface-200-800"
			>
				{#if entry.mimeType.startsWith('video/')}
					<div class="relative flex h-full w-full items-center justify-center">
						{#if !failedThumbnails.has(entry.id) && entry.thumbnailFileId}
							<AlcovesImage
								{libraryId}
								fileId={entry.thumbnailFileId}
								alt={entry.name}
								variant="card"
								sourceWidth={entry.width}
								sourceHeight={entry.height}
								class="h-full w-full object-cover"
								onerror={() => onthumbnailError?.(entry.id)}
							/>
						{:else if !failedThumbnails.has(entry.id)}
							<img
								src={apiUrl(`/api/libraries/${libraryId}/files/${entry.id}/thumbnail`)}
								alt={entry.name}
								class="h-full w-full object-cover"
								loading="lazy"
								decoding="async"
								draggable="false"
								crossorigin="use-credentials"
								onerror={() => onthumbnailError?.(entry.id)}
							/>
						{:else}
							<AppIcon name={ICONS.movie} class="size-10 text-surface-500" />
						{/if}
						{#if entry.proxyStatus === 'processing'}
							<div class="absolute inset-0 flex items-center justify-center bg-black/40">
								<AppIcon name={ICONS.loading} class="size-5 animate-spin text-white" />
							</div>
						{/if}
						{#if durationLabel}
							<span
								class="absolute right-1 bottom-1 rounded bg-black/80 px-1.5 py-0.5 text-xs leading-none font-medium text-white tabular-nums"
							>
								{durationLabel}
							</span>
						{/if}
					</div>
				{:else if isImageFile(entry)}
					{#if !failedThumbnails.has(entry.id)}
						<AlcovesImage
							{libraryId}
							fileId={entry.id}
							alt={entry.name}
							variant="card"
							sourceWidth={entry.width}
							sourceHeight={entry.height}
							class={isSmallImage(entry) ? 'object-contain' : 'h-full w-full object-cover'}
							onerror={() => onthumbnailError?.(entry.id)}
						/>
					{:else}
						<AppIcon name={ICONS.image} class="size-10 text-surface-500" />
					{/if}
				{:else}
					<AppIcon
						name={getMimeIcon(entry.mimeType)}
						class={['size-10 text-surface-500', showTrashed ? 'opacity-50' : ''].join(' ')}
					/>
				{/if}
			</div>
		{/if}
	{/if}
</div>
