// frontend/app/components/library/LibraryEntriesTable.vue
<script setup lang="ts">
import type { LibraryEntry } from "~~/shared/types/api";
import { formatDate, formatFileSize, getMimeIcon } from "~/utils/mime-icons";
import AppIcon from "~/components/AppIcon.vue";
import UserAvatar from "~/components/UserAvatar.vue";

interface Props {
  entries: LibraryEntry[];
  showTrashed: boolean;
  dragEnabled: boolean;
  draggedFileIds: string[];
  dropTargetFolderId: string | null;
  renameValue: string;
  isEntrySelected: (entry: LibraryEntry) => boolean;
  isRenaming: (entry: LibraryEntry) => boolean;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  rowClick: [entry: LibraryEntry, event: MouseEvent];
  rowDoubleClick: [entry: LibraryEntry];
  rowContextMenu: [entry: LibraryEntry, event: MouseEvent];
  dragStart: [entry: LibraryEntry, event: DragEvent];
  dragEnd: [];
  dragEnter: [entry: LibraryEntry];
  dragOver: [entry: LibraryEntry, event: DragEvent];
  dragLeave: [entry: LibraryEntry, event: DragEvent];
  drop: [entry: LibraryEntry, event: DragEvent];
  saveRename: [entry: LibraryEntry];
  cancelRename: [];
  updateRenameValue: [value: string];
}>();
</script>

<template>
  <table class="w-full">
    <thead class="sticky top-0 z-10 shadow-[0_1px_0_0] shadow-base-300/70">
      <tr>
        <th class="w-12 px-4 py-3 bg-base-100/90 backdrop-blur-sm rounded-tl-lg" />
        <th class="text-left text-xs font-medium text-muted px-4 py-3 bg-base-100/90 backdrop-blur-sm">
          Name
        </th>
        <th class="text-left text-xs font-medium text-muted px-4 py-3 bg-base-100/90 backdrop-blur-sm">
          Tags
        </th>
        <th
          class="text-left text-xs font-medium text-muted px-4 py-3 bg-base-100/90 backdrop-blur-sm hidden sm:table-cell">
          Owner
        </th>
        <th
          class="text-left text-xs font-medium text-muted px-4 py-3 bg-base-100/90 backdrop-blur-sm hidden sm:table-cell">
          {{ showTrashed ? "Trashed" : "Modified" }}
        </th>
        <th
          class="text-right text-xs font-medium text-muted px-4 py-3 bg-base-100/90 backdrop-blur-sm hidden sm:table-cell rounded-tr-lg">
          Size
        </th>
      </tr>
    </thead>
    <tbody class="select-none">
      <template v-for="entry in entries" :key="`${entry.kind}-${entry.id}`">
        <tr class="cursor-pointer transition-colors" :class="[
          props.isEntrySelected(entry)
            ? 'bg-primary/20 hover:bg-primary/28'
            : 'hover:bg-primary/10',
          props.dropTargetFolderId === entry.id && entry.kind === 'folder'
            ? 'ring-2 ring-primary/60 ring-inset bg-primary/5'
            : '',
          props.draggedFileIds.includes(entry.id) && entry.kind === 'file' ? 'opacity-60' : '',
        ]" :draggable="props.dragEnabled && entry.kind === 'file' && !props.isRenaming(entry)"
          @click="emit('rowClick', entry, $event)" @dblclick="emit('rowDoubleClick', entry)"
          @contextmenu="emit('rowContextMenu', entry, $event)" @dragstart="emit('dragStart', entry, $event)"
          @dragend="emit('dragEnd')" @dragenter="emit('dragEnter', entry)" @dragover="emit('dragOver', entry, $event)"
          @dragleave="emit('dragLeave', entry, $event)" @drop="emit('drop', entry, $event)">
          <td class="px-4 py-3">
            <div class="flex items-center justify-center">
              <AppIcon :name="entry.kind === 'folder' ? 'i-lucide-folder' : getMimeIcon(entry.mimeType)"
                class="size-5 text-muted" :class="showTrashed && entry.kind === 'file' ? 'opacity-50' : ''" />
            </div>
          </td>
          <td class="px-4 py-3 min-w-0">
            <div v-if="props.isRenaming(entry)" :data-rename-input-entry-id="entry.id">
              <input :value="renameValue" class="input input-sm w-full" autofocus
                @input="emit('updateRenameValue', ($event.target as HTMLInputElement).value)"
                @blur="emit('saveRename', entry)" @keydown.enter="emit('saveRename', entry)"
                @keydown.escape="emit('cancelRename')" @click.stop />
            </div>
            <div v-else class="flex items-center gap-1 min-w-0">
              <span v-if="entry.kind === 'folder'"
                class="text-sm font-semibold text-left truncate whitespace-nowrap block"
                :title="showTrashed ? `${entry.name} (${entry.trashFileCount ?? 0} files)` : entry.name">
                {{
                  showTrashed ? `${entry.name} (${entry.trashFileCount ?? 0} files)` : entry.name
                }}
              </span>
              <span v-else class="text-sm font-semibold text-left truncate whitespace-nowrap block"
                :class="showTrashed ? 'opacity-60' : ''" :title="entry.name">
                {{ entry.name }}
              </span>
            </div>
          </td>
          <td class="px-4 py-3">
            <div class="flex flex-wrap items-center gap-1.5">
              <span v-for="tag in entry.tags" :key="tag.id" class="size-2.5 rounded-full border border-default/50"
                :title="tag.name" :style="{ backgroundColor: tag.color }" />
            </div>
          </td>
          <td class="px-4 py-3 text-sm text-muted hidden sm:table-cell">
            <div v-if="entry.owner" class="flex items-center">
              <UserAvatar :display-name="entry.owner.displayName" :avatar-url="entry.owner.avatarUrl" size-class="w-6"
                text-size-class="text-[10px]" bg-class="bg-primary/20 text-primary" tooltip tooltip-position="right" />
            </div>
            <span v-else>-</span>
          </td>
          <td class="px-4 py-3 text-sm text-muted whitespace-nowrap hidden sm:table-cell">
            {{
              showTrashed && entry.trashedAt
                ? formatDate(entry.trashedAt)
                : formatDate(entry.updatedAt)
            }}
          </td>
          <td class="px-4 py-3 text-sm text-muted text-right whitespace-nowrap hidden sm:table-cell">
            {{ entry.kind === "folder" ? "-" : formatFileSize(entry.size) }}
          </td>
        </tr>
      </template>
    </tbody>
  </table>
</template>

// client/src/lib/components/library/LibraryEntriesTable.svelte
<script lang="ts">
	import { ICONS } from '$lib/utils/icons';
	import type { LibraryEntry } from '$lib/types/api';
	import { formatDate, formatFileSize, getMimeIcon } from '$lib/utils/mime-icons';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import UserAvatar from '$lib/components/ui/UserAvatar.svelte';

	interface Props {
		entries: LibraryEntry[];
		showTrashed: boolean;
		dragEnabled: boolean;
		draggedFileIds: string[];
		dropTargetFolderId: string | null;
		renameValue: string;
		isEntrySelected: (entry: LibraryEntry) => boolean;
		isRenaming: (entry: LibraryEntry) => boolean;
		onrowClick?: (entry: LibraryEntry, event: MouseEvent) => void;
		onrowDoubleClick?: (entry: LibraryEntry) => void;
		onrowContextMenu?: (entry: LibraryEntry, event: MouseEvent) => void;
		ondragStart?: (entry: LibraryEntry, event: DragEvent) => void;
		ondragEnd?: () => void;
		ondragEnter?: (entry: LibraryEntry) => void;
		ondragOver?: (entry: LibraryEntry, event: DragEvent) => void;
		ondragLeave?: (entry: LibraryEntry, event: DragEvent) => void;
		ondrop?: (entry: LibraryEntry, event: DragEvent) => void;
		onsaveRename?: (entry: LibraryEntry) => void;
		oncancelRename?: () => void;
		onupdateRenameValue?: (value: string) => void;
	}

	let {
		entries,
		showTrashed,
		dragEnabled,
		draggedFileIds,
		dropTargetFolderId,
		renameValue,
		isEntrySelected,
		isRenaming,
		onrowClick,
		onrowDoubleClick,
		onrowContextMenu,
		ondragStart,
		ondragEnd,
		ondragEnter,
		ondragOver,
		ondragLeave,
		ondrop,
		onsaveRename,
		oncancelRename,
		onupdateRenameValue
	}: Props = $props();
</script>

<table class="w-full">
	<thead class="sticky top-0 z-30 border-b border-surface-200-800">
		<tr>
			<th class="w-12 rounded-tl-xl bg-surface-50-950/90 px-4 py-3 backdrop-blur-sm"></th>
			<th
				class="bg-surface-50-950/90 px-4 py-3 text-left text-xs font-semibold tracking-wide text-surface-700-300 uppercase backdrop-blur-sm"
			>
				Name
			</th>
			<th
				class="bg-surface-50-950/90 px-4 py-3 text-left text-xs font-semibold tracking-wide text-surface-700-300 uppercase backdrop-blur-sm"
			>
				Tags
			</th>
			<th
				class="hidden bg-surface-50-950/90 px-4 py-3 text-left text-xs font-semibold tracking-wide text-surface-700-300 uppercase backdrop-blur-sm sm:table-cell"
			>
				Owner
			</th>
			<th
				class="hidden bg-surface-50-950/90 px-4 py-3 text-left text-xs font-semibold tracking-wide text-surface-700-300 uppercase backdrop-blur-sm sm:table-cell"
			>
				{showTrashed ? 'Trashed' : 'Modified'}
			</th>
			<th
				class="hidden rounded-tr-xl bg-surface-50-950/90 px-4 py-3 text-right text-xs font-semibold tracking-wide text-surface-700-300 uppercase backdrop-blur-sm sm:table-cell"
			>
				Size
			</th>
		</tr>
	</thead>
	<tbody class="divide-y divide-surface-200-800/60 select-none">
		{#each entries as entry (`${entry.kind}-${entry.id}`)}
			<tr
				class={[
					'cursor-pointer transition-colors',
					isEntrySelected(entry)
						? 'bg-primary-500/20 hover:bg-primary-500/30'
						: 'hover:bg-primary-500/10',
					dropTargetFolderId === entry.id && entry.kind === 'folder'
						? 'bg-primary-500/5 ring-2 ring-primary-500/60 ring-inset'
						: '',
					draggedFileIds.includes(entry.id) && entry.kind === 'file' ? 'opacity-60' : ''
				]}
				draggable={dragEnabled && entry.kind === 'file' && !isRenaming(entry)}
				onclick={(e) => onrowClick?.(entry, e)}
				ondblclick={() => onrowDoubleClick?.(entry)}
				oncontextmenu={(e) => onrowContextMenu?.(entry, e)}
				ondragstart={(e) => ondragStart?.(entry, e)}
				ondragend={() => ondragEnd?.()}
				ondragenter={() => ondragEnter?.(entry)}
				ondragover={(e) => ondragOver?.(entry, e)}
				ondragleave={(e) => ondragLeave?.(entry, e)}
				ondrop={(e) => ondrop?.(entry, e)}
			>
				<td class="px-4 py-3">
					<div class="flex items-center justify-center">
						<AppIcon
							name={entry.kind === 'folder' ? ICONS.folder : getMimeIcon(entry.mimeType)}
							class={[
								'size-5 text-surface-500',
								showTrashed && entry.kind === 'file' ? 'opacity-50' : ''
							].join(' ')}
						/>
					</div>
				</td>
				<td class="min-w-0 px-4 py-3">
					{#if isRenaming(entry)}
						<div data-rename-input-entry-id={entry.id}>
							<!-- svelte-ignore a11y_autofocus -->
							<input
								class="input w-full"
								value={renameValue}
								autofocus
								oninput={(e) => onupdateRenameValue?.((e.currentTarget as HTMLInputElement).value)}
								onblur={() => onsaveRename?.(entry)}
								onkeydown={(e) => {
									if (e.key === 'Enter') onsaveRename?.(entry);
									else if (e.key === 'Escape') oncancelRename?.();
								}}
								onclick={(e) => e.stopPropagation()}
							/>
						</div>
					{:else}
						<div class="flex min-w-0 items-center gap-1">
							{#if entry.kind === 'folder'}
								<span
									class="block truncate text-left text-sm font-semibold whitespace-nowrap"
									title={showTrashed
										? `${entry.name} (${entry.trashFileCount ?? 0} files)`
										: entry.name}
								>
									{showTrashed ? `${entry.name} (${entry.trashFileCount ?? 0} files)` : entry.name}
								</span>
							{:else}
								<span
									class={[
										'block truncate text-left text-sm font-semibold whitespace-nowrap',
										showTrashed ? 'opacity-60' : ''
									]}
									title={entry.name}
								>
									{entry.name}
								</span>
							{/if}
							{#if entry.kind === 'file' && entry.hasDuplicates}
								<span
									class="ml-1 badge gap-1 preset-tonal-warning"
									title="Duplicate of another file in this library"
								>
									<AppIcon name={ICONS.duplicate} class="size-3" />
									Duplicate
								</span>
							{/if}
						</div>
					{/if}
				</td>
				<td class="px-4 py-3">
					<div class="flex flex-wrap items-center gap-1.5">
						{#each entry.tags as tag (tag.id)}
							<span
								class="size-2.5 rounded-full border border-surface-400/50"
								title={tag.name}
								style:background-color={tag.color}
							></span>
						{/each}
					</div>
				</td>
				<td class="hidden px-4 py-3 text-sm text-surface-700-300 sm:table-cell">
					{#if entry.owner}
						<div class="flex items-center">
							<UserAvatar
								displayName={entry.owner.displayName}
								avatarUrl={entry.owner.avatarUrl}
								sizeClass="w-6"
								textSizeClass="text-[10px]"
								bgClass="preset-tonal-primary"
								tooltip
								tooltipPosition="right"
							/>
						</div>
					{:else}
						<span>-</span>
					{/if}
				</td>
				<td class="hidden px-4 py-3 text-sm whitespace-nowrap text-surface-700-300 sm:table-cell">
					{showTrashed && entry.trashedAt
						? formatDate(entry.trashedAt)
						: formatDate(entry.updatedAt)}
				</td>
				<td
					class="hidden px-4 py-3 text-right text-sm whitespace-nowrap text-surface-700-300 sm:table-cell"
				>
					{entry.kind === 'folder' ? '-' : formatFileSize(entry.size)}
				</td>
			</tr>
		{/each}
	</tbody>
</table>
