// frontend/app/components/library/LibraryEmptyState.vue
<script setup lang="ts">
import { ICONS } from "~/utils/icons";
import AppIcon from "~/components/AppIcon.vue";

interface Props {
  showTrashed: boolean;
  title: string;
  description: string;
  canManageLibrary: boolean;
}

defineProps<Props>();

const emit = defineEmits<{
  createFolder: [];
  uploadFiles: [];
}>();
</script>

<template>
  <div class="flex flex-col items-center justify-center py-16 px-4">
    <div class="size-16 rounded-full bg-elevated flex items-center justify-center mb-4">
      <AppIcon
        :name="showTrashed ? ICONS.trash : ICONS.folder"
        class="size-8 text-muted"
      />
    </div>
    <p class="text-lg font-medium text-default mb-1">{{ title }}</p>
    <p class="text-sm text-muted mb-4">{{ description }}</p>
    <div v-if="canManageLibrary && !showTrashed" class="flex items-center gap-2">
      <UButton
        color="neutral"
        variant="soft"
        :icon="ICONS.folder"
        @click="emit('createFolder')"
      >
        Create folder
      </UButton>
      <UButton color="primary" variant="soft" :icon="ICONS.upload" @click="emit('uploadFiles')">
        Upload files
      </UButton>
    </div>
  </div>
</template>

// client/src/lib/components/library/LibraryEmptyState.svelte
<script lang="ts">
	import { ICONS } from '$lib/utils/icons';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import Button from '$lib/components/ui/Button.svelte';

	interface Props {
		showTrashed: boolean;
		title: string;
		description: string;
		canManageLibrary: boolean;
		oncreateFolder?: () => void;
		onuploadFiles?: () => void;
	}

	let { showTrashed, title, description, canManageLibrary, oncreateFolder, onuploadFiles }: Props =
		$props();
</script>

<div class="flex flex-col items-center justify-center px-4 py-16">
	<div class="mb-4 flex size-16 items-center justify-center rounded-full bg-surface-200-800">
		<AppIcon name={showTrashed ? ICONS.trash : ICONS.folder} class="size-8 text-surface-500" />
	</div>
	<p class="mb-1 text-lg font-medium">{title}</p>
	<p class="mb-4 text-sm text-surface-500">{description}</p>
	{#if canManageLibrary && !showTrashed}
		<div class="flex items-center gap-2">
			<button type="button" class="btn preset-tonal" onclick={() => oncreateFolder?.()}>
				<AppIcon name={ICONS.folder} class="size-4" />
				<span>Create folder</span>
			</button>
			<Button variant="tonal" color="primary" onclick={() => onuploadFiles?.()}>
				{#snippet icon()}
					<AppIcon name={ICONS.upload} class="size-4" />
				{/snippet}
				<span>Upload files</span>
			</Button>
		</div>
	{/if}
</div>
