// client/src/lib/components/ui/ConfirmModal.svelte
<script lang="ts">
	import { Dialog } from '@skeletonlabs/skeleton-svelte';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import { ICONS } from '$lib/utils/icons';

	interface Props {
		title: string;
		message: string;
		confirmLabel: string;
		confirmClass?: string;
		confirmIcon?: string;
		pending?: boolean;
		open?: boolean;
		onconfirm?: () => void;
	}

	let {
		title,
		message,
		confirmLabel,
		confirmClass = '',
		confirmIcon = ICONS.check,
		pending = false,
		open = $bindable(false),
		onconfirm
	}: Props = $props();

	// Map the legacy Nuxt UI `confirmClass` hint onto a Button color, the same
	// substring matching the Vue original used to derive its UButton color. The
	// Button renders `preset-filled-{color}-500` — byte-equivalent to the prior
	// hand-rolled preset string.
	const confirmColor = $derived.by<'primary' | 'surface' | 'error' | 'warning' | 'success'>(() => {
		const c = confirmClass;
		if (c.includes('error')) return 'error';
		if (c.includes('warning')) return 'warning';
		if (c.includes('success')) return 'success';
		if (c.includes('neutral')) return 'surface';
		return 'primary';
	});
</script>

<Dialog {open} onOpenChange={(e) => (open = e.open)}>
	<Dialog.Backdrop class="fixed inset-0 z-40 bg-surface-950/50 backdrop-blur-sm" />
	<Dialog.Positioner class="fixed inset-0 z-50 flex items-center justify-center p-4">
		<Dialog.Content
			class="flex w-full max-w-md flex-col gap-4 card rounded-lg preset-filled-surface-50-950 p-6 shadow-xl"
		>
			<header class="flex flex-col gap-1">
				<Dialog.Title class="text-lg font-semibold">{title}</Dialog.Title>
				<Dialog.Description class="text-sm text-surface-600-400">{message}</Dialog.Description>
			</header>
			<footer class="flex w-full justify-end gap-2">
				<Button variant="tonal" color="surface" disabled={pending} onclick={() => (open = false)}>
					Cancel
				</Button>
				<Button color={confirmColor} loading={pending} onclick={() => onconfirm?.()}>
					{#snippet icon()}
						<AppIcon name={confirmIcon} class="size-4" />
					{/snippet}
					{confirmLabel}
				</Button>
			</footer>
		</Dialog.Content>
	</Dialog.Positioner>
</Dialog>

// frontend/app/components/ConfirmModal.vue
<script setup lang="ts">
import { ICONS } from "~/utils/icons";
interface Props {
  title: string;
  message: string;
  confirmLabel: string;
  confirmClass?: string;
  confirmIcon?: string;
  pending?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  confirmClass: "",
  confirmIcon: ICONS.check,
  pending: false,
});

const open = defineModel<boolean>("open", { default: false });

const emit = defineEmits<{
  confirm: [];
}>();

const confirmColor = computed<"primary" | "error" | "warning" | "success" | "neutral">(() => {
  const c = props.confirmClass;
  if (c.includes("error")) return "error";
  if (c.includes("warning")) return "warning";
  if (c.includes("success")) return "success";
  if (c.includes("neutral")) return "neutral";
  return "primary";
});
</script>

<template>
  <UModal v-model:open="open" :title="title" :description="message">
    <template #footer>
      <div class="flex justify-end gap-2 w-full">
        <UButton color="neutral" variant="ghost" :disabled="pending" @click="open = false">
          Cancel
        </UButton>
        <UButton
          :color="confirmColor"
          :icon="pending ? undefined : confirmIcon"
          :loading="pending"
          :disabled="pending"
          @click="emit('confirm')"
        >
          {{ confirmLabel }}
        </UButton>
      </div>
    </template>
  </UModal>
</template>
