// app/pages/register.vue
<script setup lang="ts">
import * as z from "zod";
import type { FormSubmitEvent, AuthFormField } from "@nuxt/ui";

definePageMeta({
  layout: false,
});

const { register } = useAuth();
const route = useRoute();
const config = useRuntimeConfig();
const error = ref("");
const googleAuthEnabled = config.public.googleAuthEnabled;
const redirectPath = computed(() => {
  const raw = route.query.redirect;
  if (typeof raw !== "string" || !raw.startsWith("/")) return "/";
  return raw;
});
const loginLink = computed(() =>
  redirectPath.value === "/"
    ? "/login"
    : {
        path: "/login",
        query: { redirect: redirectPath.value },
      },
);

const fields: AuthFormField[] = [
  {
    name: "name",
    type: "text",
    label: "Name",
    placeholder: "Enter your full name",
    required: true,
  },
  {
    name: "email",
    type: "email",
    label: "Email",
    placeholder: "Enter your email",
    required: true,
  },
  {
    name: "password",
    label: "Password",
    type: "password",
    placeholder: "Create a password",
    required: true,
  },
  {
    name: "confirmPassword",
    label: "Confirm Password",
    type: "password",
    placeholder: "Confirm your password",
    required: true,
  },
];

const schema = z
  .object({
    name: z.string().min(1, "Name is required"),
    email: z.string().email("Invalid email"),
    password: z.string().min(8, "Must be at least 8 characters"),
    confirmPassword: z.string(),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: "Passwords do not match",
    path: ["confirmPassword"],
  });

type Schema = z.output<typeof schema>;

async function onSubmit(payload: FormSubmitEvent<Schema>) {
  error.value = "";
  try {
    await register(payload.data.name, payload.data.email, payload.data.password);
    await navigateTo(redirectPath.value);
  } catch (err: unknown) {
    const msg = (err as { data?: { message?: string } })?.data?.message;
    error.value = msg || "Registration failed";
  }
}
</script>

<template>
  <UApp>
    <div class="flex min-h-svh items-center justify-center bg-default p-4">
      <UPageCard class="w-full max-w-md">
        <UAuthForm
          :schema="schema"
          :fields="fields"
          title="Create an account"
          icon="i-lucide-user-plus"
          :submit="{ label: 'Create account' }"
          @submit="onSubmit"
        >
          <template #description>
            <p class="text-sm text-muted">Get started with Alcoves.</p>
            <p v-if="error" class="text-sm text-error mt-2">{{ error }}</p>
          </template>
          <template #footer>
            <div class="space-y-4">
              <template v-if="googleAuthEnabled">
                <USeparator label="or" />
                <UButton color="neutral" variant="outline" block to="/api/auth/google" external>
                  <template #leading>
                    <svg class="w-5 h-5" viewBox="0 0 24 24">
                      <path
                        fill="#4285F4"
                        d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                      />
                      <path
                        fill="#34A853"
                        d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                      />
                      <path
                        fill="#FBBC05"
                        d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                      />
                      <path
                        fill="#EA4335"
                        d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                      />
                    </svg>
                  </template>
                  Continue with Google
                </UButton>
              </template>
              <div class="text-center text-sm">
                Already have an account?
                <ULink :to="loginLink" class="text-primary font-medium">Sign in</ULink>.
              </div>
            </div>
          </template>
        </UAuthForm>
      </UPageCard>
    </div>
  </UApp>
</template>

// client/src/routes/register/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { z } from 'zod';
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { auth } from '$lib/state/auth.svelte';
	import { api } from '$lib/api';
	import { ICONS } from '$lib/utils/icons';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import AuthCardShell from '$lib/components/ui/AuthCardShell.svelte';
	import OAuthGoogleButton from '$lib/components/ui/OAuthGoogleButton.svelte';
	import type { RegistrationMode, InviteLookupResponse } from '$lib/types/api';

	let error = $state('');

	let providersLoading = $state(true);
	let googleAuthEnabled = $state(false);

	let registrationMode = $state<RegistrationMode | null>(null);
	let invite = $state<InviteLookupResponse | null>(null);
	let inviteError = $state<string | null>(null);
	let bootLoading = $state(true);

	const inviteToken = $derived.by(() => {
		const t = page.url.searchParams.get('invite');
		return t && t.length > 0 ? t : null;
	});

	const redirectPath = $derived.by(() => {
		const raw = page.url.searchParams.get('redirect');
		if (!raw || !raw.startsWith('/')) return '/';
		return raw;
	});

	const loginLink = $derived.by(() => {
		const query = new URLSearchParams();
		if (redirectPath !== '/') query.set('redirect', redirectPath);
		if (inviteToken) query.set('invite', inviteToken);
		const qs = query.toString();
		return qs ? `/login?${qs}` : '/login';
	});

	const canRegister = $derived.by(() => {
		if (registrationMode === null) return false;
		if (registrationMode === 'open') return true;
		if (registrationMode === 'closed') return false;
		// invite_only
		return !!invite && invite.canAccept;
	});

	const disabledMessage = $derived.by(() => {
		if (registrationMode === 'closed') {
			return 'Registration is disabled on this instance.';
		}
		if (registrationMode === 'invite_only') {
			if (!inviteToken) {
				return 'Registration is invite-only. You need an invite link to create an account.';
			}
			if (inviteError) return inviteError;
			if (invite && !invite.canAccept) {
				return `This invite is ${invite.status}.`;
			}
		}
		return null;
	});

	const schema = z
		.object({
			name: z.string().min(1, 'Name is required'),
			email: z.string().email('Invalid email'),
			password: z.string().min(8, 'Must be at least 8 characters'),
			confirmPassword: z.string()
		})
		.refine((data) => data.password === data.confirmPassword, {
			message: 'Passwords do not match',
			path: ['confirmPassword']
		});

	let name = $state('');
	let email = $state('');
	let password = $state('');
	let confirmPassword = $state('');

	let fieldErrors = $state<Record<string, string>>({});
	let submitting = $state(false);

	onMount(async () => {
		try {
			const [providers, modeResp] = await Promise.all([
				api.auth.providers(),
				api.meta.registrationMode()
			]);
			googleAuthEnabled = providers.google;
			registrationMode = modeResp.mode;
		} catch (err) {
			console.error('Failed to load registration metadata:', err);
		} finally {
			providersLoading = false;
		}

		if (inviteToken) {
			try {
				invite = await api.invites.lookup(inviteToken);
				if (!invite.canAccept && invite.status !== 'already_member') {
					inviteError = `This invite is ${invite.status}.`;
				}
			} catch {
				inviteError = 'Invite not found.';
			}
		}
		bootLoading = false;
	});

	async function onSubmit() {
		error = '';
		fieldErrors = {};

		const result = schema.safeParse({ name, email, password, confirmPassword });
		if (!result.success) {
			for (const issue of result.error.issues) {
				const key = issue.path[0];
				if (typeof key === 'string' && !fieldErrors[key]) {
					fieldErrors[key] = issue.message;
				}
			}
			return;
		}

		submitting = true;
		try {
			await auth.register(name, email, password, inviteToken || undefined);
			// If they registered through an invite, send them to that library.
			if (invite?.library?.id) {
				await goto(`/libraries/${invite.library.id}`);
			} else {
				await goto(redirectPath);
			}
		} catch (err: unknown) {
			const msg = (err as { data?: { message?: string } })?.data?.message;
			error = msg || 'Registration failed';
		} finally {
			submitting = false;
		}
	}
</script>

<AuthCardShell title="Create an account" subtitle="Get started with Alcoves." {error}>
	{#if bootLoading}
		<div class="flex justify-center py-8">
			<AppIcon name={ICONS.loading} class="size-6 animate-spin opacity-60" />
		</div>
	{:else if !canRegister}
		<div class="space-y-3 py-2">
			<div class="flex items-start gap-2 card preset-tonal-warning p-3 text-sm" role="alert">
				<AppIcon name={ICONS.lock} class="mt-0.5 size-4 shrink-0" />
				<div>
					<p class="font-medium">Registration disabled</p>
					<p class="opacity-80">
						{disabledMessage || 'Registration is not available right now.'}
					</p>
				</div>
			</div>
		</div>
	{:else}
		<form
			class="space-y-4"
			onsubmit={(e) => {
				e.preventDefault();
				onSubmit();
			}}
		>
			{#if invite && invite.library}
				<div class="flex items-start gap-2 card preset-tonal-secondary p-3 text-sm" role="status">
					<AppIcon name={ICONS.email} class="mt-0.5 size-4 shrink-0" />
					<div>
						<p class="font-medium">You've been invited to {invite.library.name}</p>
						<p class="opacity-80">
							Create an account below to accept the invite. Already have one?
							<a href={loginLink} class="font-medium text-primary-500 hover:underline">
								Sign in instead
							</a>.
						</p>
					</div>
				</div>
			{/if}

			<label class="label">
				<span class="label-text">Name</span>
				<input
					class="input w-full"
					type="text"
					placeholder="Your full name"
					autocomplete="name"
					bind:value={name}
				/>
				{#if fieldErrors.name}
					<span class="text-xs text-error-500">{fieldErrors.name}</span>
				{/if}
			</label>

			<label class="label">
				<span class="label-text">Email</span>
				<input
					class="input w-full"
					type="email"
					placeholder="you@example.com"
					autocomplete="email"
					bind:value={email}
				/>
				{#if fieldErrors.email}
					<span class="text-xs text-error-500">{fieldErrors.email}</span>
				{/if}
			</label>

			<label class="label">
				<span class="label-text">Password</span>
				<input
					class="input w-full"
					type="password"
					placeholder="At least 8 characters"
					autocomplete="new-password"
					bind:value={password}
				/>
				{#if fieldErrors.password}
					<span class="text-xs text-error-500">{fieldErrors.password}</span>
				{/if}
			</label>

			<label class="label">
				<span class="label-text">Confirm password</span>
				<input
					class="input w-full"
					type="password"
					placeholder="Re-enter password"
					autocomplete="new-password"
					bind:value={confirmPassword}
				/>
				{#if fieldErrors.confirmPassword}
					<span class="text-xs text-error-500">{fieldErrors.confirmPassword}</span>
				{/if}
			</label>

			<button
				type="submit"
				class="btn w-full justify-center preset-filled-primary-500 btn-lg"
				disabled={submitting}
			>
				{#if submitting}
					<AppIcon name={ICONS.loading} class="size-4 animate-spin" />
				{/if}
				Create account
			</button>
		</form>
	{/if}

	{#snippet footer()}
		<div class="w-full space-y-4">
			{#if canRegister && !providersLoading && googleAuthEnabled}
				<div class="space-y-4">
					<div class="flex items-center gap-3 text-xs opacity-60">
						<hr class="flex-1 border-surface-200-800" />
						<span>or</span>
						<hr class="flex-1 border-surface-200-800" />
					</div>
					<OAuthGoogleButton />
				</div>
			{/if}

			<p class="text-center text-sm opacity-75">
				Already have an account?
				<a href={loginLink} class="font-medium text-primary-500 hover:underline">Sign in</a>
			</p>
		</div>
	{/snippet}
</AuthCardShell>
