// frontend/app/pages/login.vue
<script setup lang="ts">
import * as z from "zod";
import AuthCardShell from "~/components/AuthCardShell.vue";

definePageMeta({ layout: false });
import OAuthGoogleButton from "~/components/OAuthGoogleButton.vue";
import { useAuth } from "~/composables/useAuth";
import { api } from "~/api";
import type { InviteLookupResponse } from "~~/shared/types/api";

const { login } = useAuth();
const route = useRoute();
const router = useRouter();
const error = ref("");

const providersLoading = ref(true);
const googleAuthEnabled = ref(false);

const inviteToken = computed(() => {
  const t = route.query.invite;
  return typeof t === "string" && t.length > 0 ? t : null;
});
const invite = ref<InviteLookupResponse | null>(null);

onMounted(async () => {
  try {
    const providers = await api.auth.providers();
    googleAuthEnabled.value = providers.google;
  } catch (err) {
    console.error("Failed to load auth providers:", err);
  } finally {
    providersLoading.value = false;
  }

  if (inviteToken.value) {
    try {
      invite.value = await api.invites.lookup(inviteToken.value);
    } catch {
      invite.value = null;
    }
  }
});

const redirectPath = computed(() => {
  const raw = route.query.redirect;
  if (typeof raw !== "string" || !raw.startsWith("/")) return "/";
  return raw;
});
const registerLink = computed(() => {
  const query: Record<string, string> = {};
  if (redirectPath.value !== "/") query.redirect = redirectPath.value;
  if (inviteToken.value) query.invite = inviteToken.value;
  return Object.keys(query).length === 0 ? "/register" : { path: "/register", query };
});

if (route.query.error === "google") {
  error.value = "Google sign-in failed. Please try again.";
}

const schema = z.object({
  email: z.string().email("Invalid email"),
  password: z.string().min(8, "Must be at least 8 characters"),
});

const state = reactive({
  email: "",
  password: "",
});

const submitting = ref(false);

async function onSubmit() {
  error.value = "";
  submitting.value = true;
  try {
    await login(state.email, state.password);

    // If user arrived with an invite token, redeem it before navigating.
    if (inviteToken.value) {
      try {
        const result = await api.invites.accept(inviteToken.value);
        router.push(`/libraries/${result.libraryId}`);
        return;
      } catch {
        // Fall through to redirect; invite landing will surface the failure.
        router.push(`/invites/${inviteToken.value}`);
        return;
      }
    }

    router.push(redirectPath.value);
  } catch (err: unknown) {
    const msg = (err as { data?: { message?: string } })?.data?.message;
    error.value = msg || "Invalid email or password";
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <AuthCardShell
    title="Welcome back"
    subtitle="Sign in to your account to continue."
    :error="error"
  >
    <UForm :schema="schema" :state="state" class="space-y-4" @submit="onSubmit">
      <UAlert
        v-if="invite && invite.library"
        color="info"
        variant="subtle"
        icon="i-lucide-mail"
        :title="`You've been invited to ${invite.library.name}`"
        description="Sign in to accept the invite. New here? Create an account below."
      />

      <UFormField label="Email" name="email" required>
        <UInput
          v-model="state.email"
          type="email"
          placeholder="you@example.com"
          icon="i-lucide-mail"
          size="lg"
          class="w-full"
          :ui="{ root: 'w-full' }"
        />
      </UFormField>

      <UFormField label="Password" name="password" required>
        <UInput
          v-model="state.password"
          type="password"
          placeholder="••••••••"
          icon="i-lucide-lock"
          size="lg"
          class="w-full"
          :ui="{ root: 'w-full' }"
        />
      </UFormField>

      <UButton
        type="submit"
        color="primary"
        size="lg"
        :loading="submitting"
        block
        class="justify-center"
      >
        Sign in
      </UButton>
    </UForm>

    <template #footer>
      <div class="space-y-4 w-full">
        <Transition
          enter-active-class="transition-opacity duration-300"
          enter-from-class="opacity-0"
          enter-to-class="opacity-100"
        >
          <div v-if="!providersLoading && googleAuthEnabled" class="space-y-4">
            <USeparator label="or" />
            <OAuthGoogleButton />
          </div>
        </Transition>

        <p class="text-center text-sm text-muted">
          {{ invite ? "New here?" : "Don't have an account?" }}
          <NuxtLink :to="registerLink" class="text-primary font-medium hover:underline">
            {{ invite ? "Create an account" : "Sign up" }}
          </NuxtLink>
        </p>
      </div>
    </template>
  </AuthCardShell>
</template>

// client/src/routes/login/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { env } from '$env/dynamic/public';
	import { auth } from '$lib/state/auth.svelte';
	import { ApiError } from '$lib/api';
	import { ICONS } from '$lib/utils/icons';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import AuthCardShell from '$lib/components/ui/AuthCardShell.svelte';
	import OAuthGoogleButton from '$lib/components/ui/OAuthGoogleButton.svelte';

	let email = $state('');
	let password = $state('');
	let error = $state('');
	let submitting = $state(false);

	const googleAuthEnabled = env.PUBLIC_GOOGLE_AUTH_ENABLED === 'true';

	// Where to land after a successful sign-in. Only honor in-app paths so a
	// crafted `?redirect=https://evil` can't bounce the user off-site.
	const redirectPath = $derived.by(() => {
		const raw = page.url.searchParams.get('redirect');
		return raw && raw.startsWith('/') ? raw : '/';
	});

	const registerLink = $derived(
		redirectPath === '/' ? '/register' : `/register?redirect=${encodeURIComponent(redirectPath)}`
	);

	// Surface a failed Google round-trip (`?error=google`) once on load.
	$effect(() => {
		if (page.url.searchParams.get('error') === 'google') {
			error = 'Google sign-in failed. Please try again.';
		}
	});

	async function onSubmit(e: SubmitEvent) {
		e.preventDefault();
		error = '';
		submitting = true;
		try {
			await auth.login(email, password);
			await goto(redirectPath);
		} catch (err) {
			const serverMsg =
				err instanceof ApiError && typeof err.data?.message === 'string' ? err.data.message : '';
			error = serverMsg || 'Invalid email or password';
		} finally {
			submitting = false;
		}
	}
</script>

<AuthCardShell title="Welcome back" subtitle="Sign in to your account to continue." {error}>
	<form class="space-y-4" onsubmit={onSubmit}>
		<label class="label">
			<span class="label-text">Email</span>
			<div class="input-group grid grid-cols-[auto_1fr] rounded-lg preset-filled-surface-100-900">
				<span class="flex items-center justify-center pl-3 opacity-60">
					<AppIcon name={ICONS.email} class="size-4" />
				</span>
				<input
					class="bg-transparent px-2 py-2 outline-none"
					type="email"
					bind:value={email}
					placeholder="you@example.com"
					aria-label="Email"
					autocomplete="email"
					required
				/>
			</div>
		</label>

		<label class="label">
			<span class="label-text">Password</span>
			<div class="input-group grid grid-cols-[auto_1fr] rounded-lg preset-filled-surface-100-900">
				<span class="flex items-center justify-center pl-3 opacity-60">
					<AppIcon name={ICONS.lock} class="size-4" />
				</span>
				<input
					class="bg-transparent px-2 py-2 outline-none"
					type="password"
					bind:value={password}
					placeholder="••••••••"
					aria-label="Password"
					autocomplete="current-password"
					required
				/>
			</div>
		</label>

		<button
			type="submit"
			class="btn w-full justify-center preset-filled-primary-500 btn-lg"
			disabled={submitting}
		>
			{#if submitting}
				<AppIcon name={ICONS.loading} class="size-4 animate-spin" />
			{/if}
			Sign in
		</button>
	</form>

	{#snippet footer()}
		<div class="w-full space-y-4">
			{#if googleAuthEnabled}
				<div class="space-y-4">
					<div class="flex items-center gap-3 text-sm opacity-60">
						<hr class="flex-1 border-surface-200-800" />
						<span>or</span>
						<hr class="flex-1 border-surface-200-800" />
					</div>
					<OAuthGoogleButton />
				</div>
			{/if}

			<p class="text-center text-sm opacity-75">
				Don't have an account?
				<a href={registerLink} class="font-medium text-primary-500 hover:underline">Sign up</a>
			</p>
		</div>
	{/snippet}
</AuthCardShell>
