// client/src/routes/invites/[token]/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { api } from '$lib/api';
	import { ApiError } from '$lib/api';
	import { auth } from '$lib/state/auth.svelte';
	import { refreshLibraries } from '$lib/state/libraries-list.svelte';
	import { toast } from '$lib/state/toast';
	import { ICONS } from '$lib/utils/icons';
	import { cn } from '$lib/utils';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import { Button } from '$lib/components/ui/button/index.js';
	import UserAvatar from '$lib/components/ui/UserAvatar.svelte';
	import AuthCardShell from '$lib/components/ui/AuthCardShell.svelte';
	import type { InviteLookupResponse } from '$lib/types/api';

	const token = $derived(page.params.token ?? '');

	let invite = $state<InviteLookupResponse | null>(null);
	let loading = $state(true);
	let accepting = $state(false);

	// Public route (outside the authed shell), so resolve the session ourselves.
	// Anon visitors get sent to register-with-invite; once they finish registering
	// the backend auto-accepts the invite and lands them in the target library.
	onMount(async () => {
		if (!auth.loggedIn) {
			await auth.fetchSession();
			if (!auth.loggedIn) {
				goto(`/register?invite=${encodeURIComponent(token)}`);
				return;
			}
		}
		await loadInvite();
	});

	async function loadInvite() {
		loading = true;
		try {
			invite = await api.invites.lookup(token);
		} catch {
			invite = null;
		} finally {
			loading = false;
		}
	}

	const inviteTitle = $derived.by(() => {
		if (!invite) return 'Library invite';
		return `${invite.invitedBy.displayName} has invited you to join ${invite.library.name}`;
	});

	const statusMessage = $derived.by(() => {
		switch (invite?.status) {
			case 'pending':
				return 'Accept this invitation to get access to the library.';
			case 'already_member':
				return 'You already have access to this library.';
			case 'expired':
				return 'This invitation has expired.';
			case 'revoked':
				return 'This invitation was revoked by a library admin.';
			case 'exhausted':
				return 'This invitation has reached its maximum number of uses.';
			default:
				return 'Invite details unavailable.';
		}
	});

	const statusIcon = $derived.by(() => {
		switch (invite?.status) {
			case 'already_member':
				return ICONS.success;
			case 'expired':
			case 'revoked':
			case 'exhausted':
				return ICONS.error;
			default:
				return ICONS.info;
		}
	});

	const statusTone = $derived.by(() => {
		switch (invite?.status) {
			case 'already_member':
				return 'text-success';
			case 'expired':
			case 'revoked':
			case 'exhausted':
				return 'text-destructive';
			default:
				return 'text-primary';
		}
	});

	async function acceptInvite() {
		if (!invite?.canAccept) return;
		accepting = true;
		try {
			const result = await api.invites.accept(token);
			await refreshLibraries();
			toast.add({ title: 'Joined library', color: 'success' });
			goto(`/libraries/${result.libraryId}`);
		} catch (err: unknown) {
			const message =
				err instanceof ApiError
					? ((err.data?.message as string) ?? 'Failed to accept invite')
					: 'Failed to accept invite';
			toast.add({ title: message, color: 'error' });
			await loadInvite();
		} finally {
			accepting = false;
		}
	}
</script>

<AuthCardShell title="Library invite" subtitle="You'll join with member access.">
	<div class="flex flex-col gap-4">
		<div class="flex items-center gap-3">
			{#if invite}
				<UserAvatar
					displayName={invite.invitedBy.displayName}
					avatarUrl={invite.invitedBy.avatarUrl}
					size="lg"
				/>
			{/if}
			<h1 class="text-base font-semibold">{inviteTitle}</h1>
		</div>

		{#if loading}
			<div class="flex items-center justify-center py-8">
				<AppIcon name={ICONS.loading} class="size-5 animate-spin text-muted-foreground" />
			</div>
		{:else}
			<div class="flex items-start gap-2 rounded-lg bg-muted/50 p-3 text-sm" role="status">
				<AppIcon name={statusIcon} class={cn('mt-0.5 size-4 shrink-0', statusTone)} />
				<span>{statusMessage}</span>
			</div>

			<div class="flex flex-wrap items-center gap-2">
				{#if invite?.canAccept}
					<Button disabled={accepting} onclick={acceptInvite}>
						{#if accepting}
							<AppIcon name={ICONS.loading} class="size-4 animate-spin" />
						{:else}
							<AppIcon name={ICONS.check} class="size-4" />
						{/if}
						Accept Invite
					</Button>
				{/if}
				{#if invite?.library.id}
					<Button href={`/libraries/${invite.library.id}`} variant="outline">
						Go to library
						<AppIcon name={ICONS.arrowRight} class="size-4" />
					</Button>
				{/if}
			</div>
		{/if}
	</div>
</AuthCardShell>

// frontend/app/pages/invites/[token].vue
<script setup lang="ts">
import { ICONS } from "~/utils/icons";
import { useApiFetch } from "~/composables/useApiFetch";
import { api } from "~/api";
import { useAuth } from "~/composables/useAuth";
import { useToast } from "~/composables/useToast";
import UserAvatar from "~/components/UserAvatar.vue";
import type { InviteLookupResponse } from "~~/shared/types/api";

definePageMeta({ layout: "dashboard" });

const router = useRouter();
const route = useRoute();
const token = computed(() => route.params.token as string);
const toast = useToast();
const accepting = ref(false);

const { loggedIn, fetchSession } = useAuth();

// Page is whitelisted by global auth middleware, so resolve the session
// ourselves. Anon visitors get sent to register-with-invite; once they
// finish registering the backend auto-accepts the invite and lands them
// in the target library.
onMounted(async () => {
  if (loggedIn.value) return;
  await fetchSession();
  if (!loggedIn.value) {
    navigateTo({ path: "/register", query: { invite: token.value } });
  }
});

const {
  data: invite,
  status,
  refresh,
} = useApiFetch<InviteLookupResponse>(() => `/api/invites/${token.value}`);

const { refreshLibraries } = useLibrariesList();

const inviteTitle = computed(() => {
  if (!invite.value) return "Library invite";
  return `${invite.value.invitedBy.displayName} has invited you to join ${invite.value.library.name}`;
});

const statusMessage = computed(() => {
  switch (invite.value?.status) {
    case "pending":
      return "Accept this invitation to get access to the library.";
    case "already_member":
      return "You already have access to this library.";
    case "expired":
      return "This invitation has expired.";
    case "revoked":
      return "This invitation was revoked by a library admin.";
    case "exhausted":
      return "This invitation has reached its maximum number of uses.";
    default:
      return "Invite details unavailable.";
  }
});

const statusColor = computed<"primary" | "success" | "error" | "warning" | "info" | "neutral">(
  () => {
    switch (invite.value?.status) {
      case "pending":
        return "primary";
      case "already_member":
        return "success";
      case "expired":
      case "revoked":
      case "exhausted":
        return "error";
      default:
        return "neutral";
    }
  },
);

async function acceptInvite() {
  if (!invite.value?.canAccept) return;
  accepting.value = true;
  try {
    const result = await api.invites.accept(token.value);
    await refreshLibraries();
    toast.add({ title: "Joined library", color: "success" });
    router.push(`/libraries/${result.libraryId}`);
  } catch (err: unknown) {
    toast.add({
      title: (err as { data?: { message?: string } })?.data?.message ?? "Failed to accept invite",
      color: "error",
    });
    await refresh();
  } finally {
    accepting.value = false;
  }
}
</script>

<template>
  <div class="mx-auto max-w-2xl py-6 overflow-y-auto flex-1 min-h-0 px-0.5">
    <UCard>
      <template #header>
        <div class="flex items-center gap-3">
          <UserAvatar
            v-if="invite"
            :display-name="invite.invitedBy.displayName"
            :avatar-url="invite.invitedBy.avatarUrl"
            size-class="w-10"
          />
          <div>
            <h1 class="text-lg font-semibold">{{ inviteTitle }}</h1>
            <p class="text-sm text-muted">You'll join with member access.</p>
          </div>
        </div>
      </template>

      <div v-if="status === 'pending'" class="flex items-center justify-center py-8">
        <UIcon :name="ICONS.loading" class="size-5 animate-spin text-muted" />
      </div>

      <div v-else class="flex flex-col gap-4">
        <UAlert :color="statusColor" variant="soft" :description="statusMessage" />

        <div class="flex flex-wrap items-center gap-2">
          <UButton
            v-if="invite?.canAccept"
            color="primary"
            :icon="ICONS.check"
            :loading="accepting"
            @click="acceptInvite"
          >
            Accept Invite
          </UButton>
          <UButton
            v-if="invite?.library.id"
            :to="`/libraries/${invite.library.id}`"
            color="neutral"
            variant="soft"
            :trailing-icon="ICONS.arrowRight"
          >
            Go to library
          </UButton>
        </div>
      </div>
    </UCard>
  </div>
</template>
