// client/src/lib/components/profile/AccessTokensSection.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import AppPanel from '$lib/components/ui/AppPanel.svelte';
	import AppModal from '$lib/components/ui/AppModal.svelte';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import { ICONS } from '$lib/utils/icons';
	import { api } from '$lib/api';
	import { toast } from '$lib/state/toast';
	import type { AccessToken, CreatedAccessToken } from '$lib/types/api';

	/**
	 * MCP access-token management. Lists the user's tokens, lets them mint a new one
	 * (the plaintext is shown exactly once in a modal right after creation), and
	 * revoke existing tokens. Backed by api.auth.listTokens/createToken/revokeToken.
	 */

	let tokens = $state<AccessToken[]>([]);

	let newName = $state('');
	let newExpiry = $state('never');
	let creating = $state(false);
	let revokingId = $state<string | null>(null);

	// The plaintext token is shown exactly once, in a modal, right after creation.
	let createdToken = $state<CreatedAccessToken | null>(null);
	let showCreated = $state(false);

	const expiryOptions = [
		{ label: 'Never expires', value: 'never' },
		{ label: '30 days', value: '30' },
		{ label: '90 days', value: '90' },
		{ label: '1 year', value: '365' }
	];

	async function refresh() {
		try {
			tokens = await api.auth.listTokens();
		} catch {
			// Leave the current list in place on a transient fetch error.
		}
	}

	onMount(refresh);

	async function createToken() {
		const name = newName.trim();
		if (!name) {
			toast.add({ title: 'Give the token a name', color: 'error' });
			return;
		}
		creating = true;
		try {
			const expiresInDays = newExpiry === 'never' ? null : Number(newExpiry);
			const created = await api.auth.createToken({ name, expiresInDays });
			createdToken = created;
			showCreated = true;
			newName = '';
			newExpiry = 'never';
			await refresh();
		} catch (err: unknown) {
			const msg =
				(err as { data?: { message?: string } })?.data?.message ?? 'Failed to create token';
			toast.add({ title: msg, color: 'error' });
		} finally {
			creating = false;
		}
	}

	async function revokeToken(id: string) {
		revokingId = id;
		try {
			await api.auth.revokeToken(id);
			toast.add({ title: 'Token revoked', color: 'success' });
			await refresh();
		} catch {
			toast.add({ title: 'Failed to revoke token', color: 'error' });
		} finally {
			revokingId = null;
		}
	}

	async function copyToken() {
		if (!createdToken) return;
		try {
			await navigator.clipboard.writeText(createdToken.token);
			toast.add({ title: 'Token copied to clipboard', color: 'success' });
		} catch {
			toast.add({ title: 'Could not copy — select and copy manually', color: 'error' });
		}
	}

	function formatDate(value: string | null): string {
		if (!value) return 'never';
		return new Date(value).toLocaleDateString('en-US', {
			year: 'numeric',
			month: 'short',
			day: 'numeric',
			timeZone: 'UTC'
		});
	}

	// Clear the captured plaintext once the show-once modal closes.
	$effect(() => {
		if (!showCreated) createdToken = null;
	});
</script>

<AppPanel
	title="MCP access tokens"
	description="Connect the Alcoves MCP server. A token acts as you — it can only read and change what you can."
	icon={ICONS.key}
>
	{#snippet actions()}
		<span class="badge preset-tonal-surface">{tokens.length} active</span>
	{/snippet}

	<div class="space-y-5">
		<!-- Create -->
		<div class="flex flex-col gap-2 sm:flex-row sm:items-end">
			<label class="flex-1 space-y-1">
				<span class="block text-sm font-medium">Name</span>
				<input
					class="input w-full"
					placeholder="e.g. Claude Desktop on laptop"
					bind:value={newName}
					disabled={creating}
					onkeyup={(e) => {
						if (e.key === 'Enter') createToken();
					}}
				/>
				<span class="block text-xs text-surface-600-400">What is this token for?</span>
			</label>
			<label class="space-y-1">
				<span class="block text-sm font-medium">Expires</span>
				<select class="select" bind:value={newExpiry} disabled={creating}>
					{#each expiryOptions as opt (opt.value)}
						<option value={opt.value}>{opt.label}</option>
					{/each}
				</select>
			</label>
			<Button loading={creating} disabled={creating} onclick={createToken}>
				{#snippet icon()}
					<AppIcon name={ICONS.plus} class="size-4" />
				{/snippet}
				Create token
			</Button>
		</div>

		<hr class="border-surface-200-800" />

		<!-- List -->
		{#if tokens.length}
			<div class="overflow-hidden rounded-md border border-surface-200-800">
				{#each tokens as token (token.id)}
					<div
						class="flex flex-col gap-2 border-b border-surface-200-800 px-4 py-3 last:border-b-0 md:flex-row md:items-center"
					>
						<div class="flex min-w-0 flex-1 items-center gap-3">
							<div
								class="flex size-9 shrink-0 items-center justify-center rounded-full preset-tonal-surface"
							>
								<AppIcon name={ICONS.key} class="size-4" />
							</div>
							<div class="min-w-0">
								<p class="truncate text-sm font-medium">{token.name}</p>
								<div
									class="flex flex-wrap items-center gap-x-2 gap-y-0.5 text-xs text-surface-600-400"
								>
									<span>Created {formatDate(token.createdAt)}</span>
									<span aria-hidden="true">·</span>
									<span>Expires {formatDate(token.expiresAt)}</span>
									<span aria-hidden="true">·</span>
									<span>
										{token.lastUsedAt ? `Last used ${formatDate(token.lastUsedAt)}` : 'Never used'}
									</span>
								</div>
							</div>
						</div>
						<Button
							variant="tonal"
							color="error"
							size="sm"
							loading={revokingId === token.id}
							disabled={revokingId === token.id}
							onclick={() => revokeToken(token.id)}
						>
							{#snippet icon()}
								<AppIcon name={ICONS.trash} class="size-4" />
							{/snippet}
							Revoke
						</Button>
					</div>
				{/each}
			</div>
		{:else}
			<div class="flex items-start gap-3 card preset-tonal-surface p-4">
				<AppIcon name={ICONS.key} class="size-5 shrink-0 opacity-70" />
				<div class="space-y-0.5">
					<p class="text-sm font-medium">No access tokens yet</p>
					<p class="text-xs text-surface-600-400">
						Create one to connect an MCP client to your Alcoves libraries.
					</p>
				</div>
			</div>
		{/if}
	</div>
</AppPanel>

<!-- Show-once token modal -->
<AppModal
	bind:open={showCreated}
	title="Copy your new token"
	description="This is the only time the token is shown. Store it somewhere safe."
>
	<div class="space-y-4">
		<div class="flex items-center gap-2">
			<input class="input w-full font-mono text-xs" value={createdToken?.token ?? ''} readonly />
			<Button
				iconOnly
				variant="tonal"
				color="surface"
				class="shrink-0"
				aria-label="Copy token"
				onclick={copyToken}
			>
				{#snippet icon()}
					<AppIcon name={ICONS.copy} class="size-4" />
				{/snippet}
			</Button>
		</div>
		<div class="flex items-start gap-3 card preset-tonal-warning p-4">
			<AppIcon name={ICONS.shield} class="size-5 shrink-0 opacity-80" />
			<div class="space-y-0.5">
				<p class="text-sm font-medium">Treat it like a password</p>
				<p class="text-xs opacity-80">
					Anyone with this token can access your libraries as you. Revoke it if it leaks.
				</p>
			</div>
		</div>
		<div class="flex w-full justify-end">
			<Button onclick={() => (showCreated = false)}>Done</Button>
		</div>
	</div>
</AppModal>

// frontend/app/components/profile/AccessTokensSection.vue
<script setup lang="ts">
import { useApiFetch } from "~/composables/useApiFetch";
import { api } from "~/api";
import { useToast } from "~/composables/useToast";
import type { AccessToken, CreatedAccessToken } from "~~/shared/types/api";

const toast = useToast();

const { data: tokens, refresh } = useApiFetch<AccessToken[]>("/api/auth/tokens");

const newName = ref("");
const newExpiry = ref<string>("never");
const creating = ref(false);
const revokingId = ref<string | null>(null);

// The plaintext token is shown exactly once, in a modal, right after creation.
const createdToken = ref<CreatedAccessToken | null>(null);
const showCreated = computed({
  get: () => createdToken.value !== null,
  set: (v: boolean) => {
    if (!v) createdToken.value = null;
  },
});

const expiryOptions = [
  { label: "Never expires", value: "never" },
  { label: "30 days", value: "30" },
  { label: "90 days", value: "90" },
  { label: "1 year", value: "365" },
];

async function createToken() {
  const name = newName.value.trim();
  if (!name) {
    toast.add({ title: "Give the token a name", color: "error" });
    return;
  }
  creating.value = true;
  try {
    const expiresInDays = newExpiry.value === "never" ? null : Number(newExpiry.value);
    const created = await api.auth.createToken({ name, expiresInDays });
    createdToken.value = created;
    newName.value = "";
    newExpiry.value = "never";
    await refresh();
  } catch (err: unknown) {
    const msg = (err as { data?: { message?: string } })?.data?.message ?? "Failed to create token";
    toast.add({ title: msg, color: "error" });
  } finally {
    creating.value = false;
  }
}

async function revokeToken(id: string) {
  revokingId.value = id;
  try {
    await api.auth.revokeToken(id);
    toast.add({ title: "Token revoked", color: "success" });
    await refresh();
  } catch {
    toast.add({ title: "Failed to revoke token", color: "error" });
  } finally {
    revokingId.value = null;
  }
}

async function copyToken() {
  if (!createdToken.value) return;
  try {
    await navigator.clipboard.writeText(createdToken.value.token);
    toast.add({ title: "Token copied to clipboard", color: "success" });
  } catch {
    toast.add({ title: "Could not copy — select and copy manually", color: "error" });
  }
}

function formatDate(value: string | null): string {
  if (!value) return "never";
  return new Date(value).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    timeZone: "UTC",
  });
}
</script>

<template>
  <AppPanel
    title="MCP access tokens"
    description="Connect the Alcoves MCP server. A token acts as you — it can only read and change what you can."
    icon="i-lineicons-key"
  >
    <template #actions>
      <UBadge color="neutral" variant="soft">{{ tokens?.length ?? 0 }} active</UBadge>
    </template>

    <div class="space-y-5">
      <!-- Create -->
      <div class="flex flex-col gap-2 sm:flex-row sm:items-end">
        <UFormField label="Name" hint="What is this token for?" class="flex-1">
          <UInput
            v-model="newName"
            placeholder="e.g. Claude Desktop on laptop"
            class="w-full"
            :ui="{ root: 'w-full' }"
            :disabled="creating"
            @keyup.enter="createToken"
          />
        </UFormField>
        <UFormField label="Expires">
          <USelect v-model="newExpiry" :items="expiryOptions" :disabled="creating" />
        </UFormField>
        <UButton
          color="primary"
          icon="i-lineicons-plus"
          :loading="creating"
          :disabled="creating"
          @click="createToken"
        >
          Create token
        </UButton>
      </div>

      <USeparator />

      <!-- List -->
      <div
        v-if="tokens?.length"
        class="divide-y divide-default overflow-hidden rounded-md bg-elevated"
      >
        <div
          v-for="token in tokens"
          :key="token.id"
          class="flex flex-col gap-2 px-4 py-3 md:flex-row md:items-center"
        >
          <div class="flex min-w-0 flex-1 items-center gap-3">
            <div
              class="flex size-9 shrink-0 items-center justify-center rounded-full bg-default text-dimmed"
            >
              <UIcon name="i-lineicons-key" class="size-4" />
            </div>
            <div class="min-w-0">
              <p class="truncate text-sm font-medium text-highlighted">{{ token.name }}</p>
              <div class="flex flex-wrap items-center gap-x-2 gap-y-0.5 text-xs text-muted">
                <span>Created {{ formatDate(token.createdAt) }}</span>
                <span aria-hidden="true">·</span>
                <span>Expires {{ formatDate(token.expiresAt) }}</span>
                <span aria-hidden="true">·</span>
                <span>{{
                  token.lastUsedAt ? `Last used ${formatDate(token.lastUsedAt)}` : "Never used"
                }}</span>
              </div>
            </div>
          </div>
          <UButton
            color="error"
            variant="soft"
            size="sm"
            icon="i-lineicons-trash-can"
            :loading="revokingId === token.id"
            :disabled="revokingId === token.id"
            @click="revokeToken(token.id)"
          >
            Revoke
          </UButton>
        </div>
      </div>
      <UAlert
        v-else
        color="neutral"
        variant="soft"
        icon="i-lineicons-key"
        title="No access tokens yet"
        description="Create one to connect an MCP client to your Alcoves libraries."
      />
    </div>

    <!-- Show-once token modal -->
    <UModal
      v-model:open="showCreated"
      title="Copy your new token"
      description="This is the only time the token is shown. Store it somewhere safe."
    >
      <template #body>
        <div class="space-y-3">
          <div class="flex items-center gap-2">
            <UInput
              :model-value="createdToken?.token ?? ''"
              readonly
              class="w-full font-mono text-xs"
              :ui="{ root: 'w-full' }"
            />
            <UButton color="neutral" icon="i-lineicons-clipboard" square @click="copyToken" />
          </div>
          <UAlert
            color="warning"
            variant="soft"
            icon="i-lineicons-shield-2"
            title="Treat it like a password"
            description="Anyone with this token can access your libraries as you. Revoke it if it leaks."
          />
        </div>
      </template>
      <template #footer>
        <div class="flex w-full justify-end">
          <UButton color="primary" @click="showCreated = false">Done</UButton>
        </div>
      </template>
    </UModal>
  </AppPanel>
</template>
