// frontend/app/pages/libraries/[id]/map.vue
<script setup lang="ts">
import { ICONS } from "~/utils/icons";
import { onMounted, ref } from "vue";
import { useLibraryMap } from "~/composables/useLibraryMap";
import { api } from "~/api";
import type { LibraryFile, MapPoint } from "~~/shared/types/api";
import AppIcon from "~/components/AppIcon.vue";
import FilePreview from "~/components/FilePreview.vue";

definePageMeta({ layout: "library" });

const route = useRoute();
const libraryId = computed(() => route.params.id as string);

const map = useLibraryMap(libraryId);

const previewFile = ref<LibraryFile | null>(null);
const previewOpen = ref(false);

// Ordered, lightweight LibraryFile records for every geotagged point so the
// lightbox can page through the whole map. Map points are a thin DTO, so the
// displayed file is always (re)fetched in full on open and on navigate.
const previewFiles = computed<LibraryFile[]>(() =>
  map.points.value.map((p) => ({
    id: p.id,
    libraryId: libraryId.value,
    parentFolderId: null,
    name: p.name,
    kind: "file",
    mimeType: "",
    size: 0,
    duration: null,
    width: null,
    height: null,
    proxyStatus: null,
    thumbnailFileId: p.thumbnailFileId,
    sourceFileId: null,
    originalCreatedAt: null,
    capturedAt: p.capturedAt,
    gpsLat: p.lat,
    gpsLon: p.lon,
    hash: null,
    trashedAt: null,
    createdAt: p.capturedAt ?? "",
    updatedAt: p.capturedAt ?? "",
    owner: null,
    tags: [],
  })),
);

// Map points are a thin DTO; fetch the full file before opening the lightbox.
async function onSelect(point: MapPoint) {
  try {
    const file = await api.files.get(libraryId.value, point.id);
    previewFile.value = file;
    previewOpen.value = true;
  } catch {
    // Ignore — file may have been removed since the map loaded.
  }
}

// Lightbox prev/next emits one of the thin previewFiles records — refetch it in
// full so the preview has real mime/proxy data, mirroring onSelect.
async function onNavigate(file: LibraryFile) {
  try {
    previewFile.value = await api.files.get(libraryId.value, file.id);
  } catch {
    // Ignore — file may have been removed since the map loaded.
  }
}

function handleFileUpdate(updated: LibraryFile) {
  if (previewFile.value?.id === updated.id) {
    previewFile.value = { ...previewFile.value, ...updated };
  }
}

onMounted(() => {
  void map.load();
});
</script>

<template>
  <div class="flex flex-col h-full">
    <div class="flex items-center justify-between gap-3 px-4 py-3 border-b border-default">
      <div class="min-w-0">
        <h2 class="text-base font-semibold text-default">Map</h2>
        <p class="text-xs text-muted mt-0.5">Where your photos were taken.</p>
      </div>
      <span v-if="map.points.value.length > 0" class="text-xs text-muted shrink-0">
        {{ map.points.value.length }} geotagged
      </span>
    </div>

    <div
      v-if="map.truncated.value"
      class="px-4 py-2 text-xs text-warning bg-warning/10 border-b border-default"
    >
      Showing the most recent {{ map.points.value.length }} geotagged files. Some points are not
      displayed.
    </div>

    <div class="relative flex-1 min-h-0">
      <!-- Loading -->
      <div
        v-if="map.loading.value && map.points.value.length === 0"
        class="absolute inset-0 z-10 flex items-center justify-center text-sm text-muted"
      >
        <AppIcon :name="ICONS.loading" class="size-5 animate-spin" />
      </div>

      <!-- Error -->
      <div
        v-else-if="map.error.value"
        class="absolute inset-0 z-10 flex items-center justify-center px-4 text-center text-sm text-error"
      >
        {{ map.error.value }}
      </div>

      <!-- Empty -->
      <div
        v-else-if="!map.loading.value && map.points.value.length === 0"
        class="absolute inset-0 z-10 flex flex-col items-center justify-center px-4 text-center text-sm text-muted"
      >
        <AppIcon :name="ICONS.location" class="size-8 mb-3 opacity-40" />
        <p>No geotagged photos yet.</p>
        <p class="mt-1 text-xs">
          Photos with GPS metadata appear here once their location is extracted.
        </p>
      </div>

      <!-- Map (client-only component). Only mounted once there are points to
           plot, so an empty/loading library never fetches map tiles. -->
      <LibraryMap
        v-if="map.points.value.length > 0"
        :points="map.points.value"
        class="absolute inset-0"
        @select="onSelect"
      />
    </div>

    <FilePreview
      v-if="previewFile"
      v-model:open="previewOpen"
      :file="previewFile"
      :library-id="libraryId"
      :files="previewFiles"
      @navigate="onNavigate"
      @update:file="handleFileUpdate"
    />
  </div>
</template>

// client/src/routes/(app)/libraries/[id]/map/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { ICONS } from '$lib/utils/icons';
	import { createLibraryMap } from '$lib/state/library-map.svelte';
	import { api } from '$lib/api';
	import type { LibraryFile, MapPoint } from '$lib/types/api';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import FilePreview from '$lib/components/FilePreview.svelte';
	import LibraryMap from '$lib/components/LibraryMap.svelte';

	const libraryId = $derived(page.params.id ?? '');

	const map = createLibraryMap();

	let previewFile = $state<LibraryFile | null>(null);
	let previewOpen = $state(false);

	// Ordered, lightweight LibraryFile records for every geotagged point so the
	// lightbox can page through the whole map. Map points are a thin DTO, so the
	// displayed file is always (re)fetched in full on open and on navigate.
	const previewFiles = $derived<LibraryFile[]>(
		map.points.map((p) => ({
			id: p.id,
			libraryId,
			parentFolderId: null,
			name: p.name,
			kind: 'file',
			mimeType: '',
			size: 0,
			duration: null,
			width: null,
			height: null,
			proxyStatus: null,
			thumbnailFileId: p.thumbnailFileId,
			sourceFileId: null,
			originalCreatedAt: null,
			capturedAt: p.capturedAt,
			gpsLat: p.lat,
			gpsLon: p.lon,
			hash: null,
			trashedAt: null,
			createdAt: p.capturedAt ?? '',
			updatedAt: p.capturedAt ?? '',
			owner: null,
			tags: []
		}))
	);

	// Map points are a thin DTO; fetch the full file before opening the lightbox.
	async function onSelect(point: MapPoint) {
		try {
			const file = await api.files.get(libraryId, point.id);
			previewFile = file;
			previewOpen = true;
		} catch {
			// Ignore — file may have been removed since the map loaded.
		}
	}

	// Lightbox prev/next emits one of the thin previewFiles records — refetch it in
	// full so the preview has real mime/proxy data, mirroring onSelect.
	async function onNavigate(file: LibraryFile) {
		try {
			previewFile = await api.files.get(libraryId, file.id);
		} catch {
			// Ignore — file may have been removed since the map loaded.
		}
	}

	onMount(() => {
		void map.load(libraryId);
	});
</script>

<div class="flex h-full flex-col">
	<div class="flex items-center justify-between gap-3 border-b border-surface-200-800 px-4 py-3">
		<div class="min-w-0">
			<h2 class="text-base font-semibold">Map</h2>
			<p class="mt-0.5 text-xs text-surface-500">Where your photos were taken.</p>
		</div>
		{#if map.points.length > 0}
			<span class="shrink-0 text-xs text-surface-500">
				{map.points.length} geotagged
			</span>
		{/if}
	</div>

	{#if map.truncated}
		<div
			class="border-b border-surface-200-800 bg-warning-500/10 px-4 py-2 text-xs text-warning-600"
		>
			Showing the most recent {map.points.length} geotagged files. Some points are not displayed.
		</div>
	{/if}

	<div class="relative min-h-0 flex-1">
		<!-- Loading -->
		{#if map.loading && map.points.length === 0}
			<div class="absolute inset-0 z-10 flex items-center justify-center text-sm text-surface-500">
				<AppIcon name={ICONS.loading} class="size-5 animate-spin" />
			</div>
			<!-- Error -->
		{:else if map.error}
			<div
				class="absolute inset-0 z-10 flex items-center justify-center px-4 text-center text-sm text-error-500"
			>
				{map.error}
			</div>
			<!-- Empty -->
		{:else if !map.loading && map.points.length === 0}
			<div
				class="absolute inset-0 z-10 flex flex-col items-center justify-center px-4 text-center text-sm text-surface-500"
			>
				<AppIcon name={ICONS.location} class="mb-3 size-8 opacity-40" />
				<p>No geotagged photos yet.</p>
				<p class="mt-1 text-xs">
					Photos with GPS metadata appear here once their location is extracted.
				</p>
			</div>
		{/if}

		<!-- Map (client-only component). Only mounted once there are points to
		     plot, so an empty/loading library never fetches map tiles. The map
		     component fills its own h-full/w-full root; wrap it so it overlays the
		     relative container. -->
		{#if map.points.length > 0}
			<div class="absolute inset-0">
				<LibraryMap points={map.points} onselect={onSelect} />
			</div>
		{/if}
	</div>

	{#if previewFile}
		<FilePreview
			bind:open={previewOpen}
			file={previewFile}
			{libraryId}
			files={previewFiles}
			onnavigate={onNavigate}
		/>
	{/if}
</div>
