// app/pages/search.vue
<script setup lang="ts">
import type { GlobalSearchResponse, GlobalSearchResult } from "~~/shared/types/api";
import { formatDate, formatFileSize, getMimeIcon } from "~/utils/mime-icons";

definePageMeta({
  layout: "dashboard",
});

const MIN_QUERY_LENGTH = 2;
const SEARCH_LIMIT = 80;

const route = useRoute();
const searchInput = ref("");

const routeSearchQuery = computed(() => {
  const raw = route.query.q;
  return typeof raw === "string" ? raw : "";
});
const activeQuery = computed(() => routeSearchQuery.value.trim());

watch(
  routeSearchQuery,
  (value) => {
    searchInput.value = value;
  },
  { immediate: true },
);

function createEmptySearchResponse(query = ""): GlobalSearchResponse {
  return {
    query,
    totalCount: 0,
    results: [],
  };
}

const {
  data: searchData,
  status,
  error,
  execute,
} = await useFetch<GlobalSearchResponse>("/api/search", {
  query: computed(() => ({
    q: activeQuery.value,
    limit: String(SEARCH_LIMIT),
  })),
  immediate: false,
  default: () => createEmptySearchResponse(),
});

watch(
  activeQuery,
  async (value) => {
    if (value.length < MIN_QUERY_LENGTH) {
      searchData.value = createEmptySearchResponse(value);
      return;
    }

    await execute();
  },
  { immediate: true },
);

async function submitSearch() {
  const query = searchInput.value.trim();
  await navigateTo(query ? { path: "/search", query: { q: query } } : { path: "/search" });
}

const results = computed(() => searchData.value?.results ?? []);
const groupedResults = computed(() => {
  const groups: Array<{
    libraryId: string;
    libraryName: string;
    results: GlobalSearchResult[];
  }> = [];
  const byLibraryId = new Map<
    string,
    {
      libraryId: string;
      libraryName: string;
      results: GlobalSearchResult[];
    }
  >();

  for (const result of results.value) {
    let group = byLibraryId.get(result.libraryId);
    if (!group) {
      group = {
        libraryId: result.libraryId,
        libraryName: result.libraryName,
        results: [],
      };
      byLibraryId.set(result.libraryId, group);
      groups.push(group);
    }

    group.results.push(result);
  }

  return groups;
});

function getResultLink(result: GlobalSearchResult) {
  if (result.targetFolderId) {
    return {
      path: `/libraries/${result.libraryId}`,
      query: { folder: result.targetFolderId },
    };
  }

  return {
    path: `/libraries/${result.libraryId}`,
  };
}

function getResultIcon(result: GlobalSearchResult): string {
  if (result.kind === "folder") return "i-lucide-folder";
  return getMimeIcon(result.mimeType ?? "application/octet-stream");
}
</script>

<template>
  <div class="mx-auto w-full max-w-6xl space-y-6">
    <UCard
      variant="subtle"
      :ui="{
        root: 'overflow-hidden bg-gradient-to-br from-primary/10 via-elevated to-default shadow-sm',
        body: 'space-y-4',
      }"
    >
      <div class="space-y-1">
        <h1 class="text-2xl font-semibold">Global Search</h1>
        <p class="text-sm text-muted">
          Search files and folders across every library you can access.
        </p>
      </div>

      <form class="flex flex-col gap-3 md:flex-row md:items-center" @submit.prevent="submitSearch">
        <UInput
          v-model="searchInput"
          type="search"
          leading-icon="i-lucide-search"
          placeholder="Search all libraries..."
          autocomplete="off"
          enterkeyhint="search"
          class="w-full"
          :ui="{
            root: 'rounded-xl',
          }"
        />
        <UButton type="submit" icon="i-lucide-search" label="Search" />
      </form>

      <div class="flex flex-wrap items-center gap-2 text-xs text-muted">
        <UBadge color="neutral" variant="subtle"
          >{{ searchData?.totalCount ?? 0 }} total matches</UBadge
        >
        <UBadge color="neutral" variant="subtle">{{ results.length }} shown</UBadge>
        <span v-if="(searchData?.totalCount ?? 0) > results.length">
          Showing the top {{ results.length }} most relevant results.
        </span>
      </div>
    </UCard>

    <UCard v-if="activeQuery.length < MIN_QUERY_LENGTH" variant="soft">
      <div class="flex items-center gap-3 text-muted">
        <UIcon name="i-lucide-search-check" class="size-5" />
        <p>Enter at least {{ MIN_QUERY_LENGTH }} characters to start searching.</p>
      </div>
    </UCard>

    <div v-else-if="status === 'pending'" class="flex items-center justify-center py-12">
      <UIcon name="i-lucide-loader-2" class="size-6 animate-spin text-muted" />
    </div>

    <UCard v-else-if="error" variant="soft">
      <div class="flex items-center gap-3 text-error">
        <UIcon name="i-lucide-alert-circle" class="size-5" />
        <p>Search failed. Try again in a moment.</p>
      </div>
    </UCard>

    <UCard v-else-if="!results.length" variant="soft">
      <div class="flex items-center gap-3 text-muted">
        <UIcon name="i-lucide-folder-search" class="size-5" />
        <p>No results found for "{{ activeQuery }}".</p>
      </div>
    </UCard>

    <div v-else class="space-y-4">
      <UCard
        v-for="group in groupedResults"
        :key="group.libraryId"
        variant="soft"
        :ui="{
          body: 'p-0',
        }"
      >
        <template #header>
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2">
              <UIcon name="i-lucide-library" class="size-4 text-primary" />
              <h2 class="font-semibold">{{ group.libraryName }}</h2>
            </div>
            <UBadge color="neutral" variant="subtle">{{ group.results.length }}</UBadge>
          </div>
        </template>

        <div class="space-y-1 p-1">
          <NuxtLink
            v-for="result in group.results"
            :key="`${result.kind}-${result.id}`"
            :to="getResultLink(result)"
            class="group flex items-center gap-3 rounded-lg px-4 py-3 transition-colors hover:bg-elevated/70"
          >
            <div
              class="flex size-10 shrink-0 items-center justify-center rounded-lg bg-elevated/80"
            >
              <UIcon :name="getResultIcon(result)" class="size-4 text-primary" />
            </div>

            <div class="min-w-0 flex-1">
              <p class="truncate text-sm font-medium">{{ result.name }}</p>
              <p class="truncate font-mono text-[11px] text-muted">{{ result.locationPath }}</p>
            </div>

            <div class="hidden shrink-0 items-center gap-2 md:flex">
              <span class="text-xs text-muted">{{ formatDate(result.updatedAt) }}</span>
              <UBadge color="neutral" variant="soft" size="sm">{{ result.kind }}</UBadge>
              <UBadge
                v-if="result.kind === 'file' && typeof result.size === 'number'"
                color="neutral"
                variant="subtle"
                size="sm"
              >
                {{ formatFileSize(result.size) }}
              </UBadge>
            </div>

            <UIcon
              name="i-lucide-arrow-up-right"
              class="size-4 shrink-0 text-muted transition-colors group-hover:text-primary"
            />
          </NuxtLink>
        </div>
      </UCard>
    </div>
  </div>
</template>

// client/src/routes/(app)/search/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { ICONS } from '$lib/utils/icons';
	import { api } from '$lib/api';
	import type { GalleryGroup } from '$lib/utils/gallery-types';
	import type { GlobalSearchResponse, GlobalSearchResult, LibraryFile } from '$lib/types/api';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import EmptyState from '$lib/components/ui/EmptyState.svelte';
	import JustifiedGallery from '$lib/components/JustifiedGallery.svelte';
	import FilePreview from '$lib/components/FilePreview.svelte';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import * as Alert from '$lib/components/ui/alert/index.js';

	const MIN_QUERY_LENGTH = 2;
	const SEARCH_LIMIT = 80;

	// `q` comes from the global search bar in the dashboard header, which pushes it
	// into the URL. This page owns no input of its own — it only reacts to the URL.
	const activeQuery = $derived((page.url.searchParams.get('q') ?? '').trim());

	function createEmptySearchResponse(query = ''): GlobalSearchResponse {
		return { query, totalCount: 0, results: [] };
	}

	let searchData = $state<GlobalSearchResponse>(createEmptySearchResponse());
	let status = $state<'idle' | 'pending' | 'success' | 'error'>('idle');

	// Re-run the search whenever the active query changes. A query shorter than the
	// minimum just clears the results (no request); a longer one fetches and races
	// are guarded by comparing the captured query against the latest one.
	$effect(() => {
		const query = activeQuery;
		if (query.length < MIN_QUERY_LENGTH) {
			searchData = createEmptySearchResponse(query);
			status = 'idle';
			return;
		}

		let cancelled = false;
		status = 'pending';
		api.search
			.query({ q: query, limit: String(SEARCH_LIMIT) })
			.then((data) => {
				if (cancelled) return;
				searchData = data;
				status = 'success';
			})
			.catch(() => {
				if (cancelled) return;
				searchData = createEmptySearchResponse(query);
				status = 'error';
			});

		return () => {
			cancelled = true;
		};
	});

	const results = $derived(searchData.results ?? []);

	function isVideoResult(result: GlobalSearchResult): boolean {
		return (result.mimeType ?? '').startsWith('video/');
	}

	// Thumbnail source: the file itself for images, the generated poster for videos,
	// null (→ icon tile) for folders and non-media files.
	function getThumbnailFileId(result: GlobalSearchResult): string | null {
		if (result.kind !== 'file') return null;
		const mime = result.mimeType ?? '';
		if (mime.startsWith('image/')) return result.id;
		if (mime.startsWith('video/') && result.thumbnailFileId) return result.thumbnailFileId;
		return null;
	}

	function aspectOf(result: GlobalSearchResult): number {
		if (result.width && result.height && result.width > 0 && result.height > 0) {
			return result.width / result.height;
		}
		// Folders read as wide tiles; everything else falls back to square.
		return result.kind === 'folder' ? 1.6 : 1;
	}

	// Group results by library, mapped into the shared gallery shape. The library
	// name is the sticky heading; matched object labels become a tile badge.
	const galleryGroups = $derived.by<GalleryGroup<GlobalSearchResult>[]>(() => {
		const groups: GalleryGroup<GlobalSearchResult>[] = [];
		const byLibraryId = new Map<string, GalleryGroup<GlobalSearchResult>>();

		for (const result of results) {
			let group = byLibraryId.get(result.libraryId);
			if (!group) {
				group = { key: result.libraryId, heading: result.libraryName, count: 0, items: [] };
				byLibraryId.set(result.libraryId, group);
				groups.push(group);
			}
			group.items.push({
				id: `${result.kind}-${result.id}`,
				libraryId: result.libraryId,
				thumbnailFileId: getThumbnailFileId(result),
				aspect: aspectOf(result),
				mime:
					result.kind === 'folder'
						? 'inode/directory'
						: (result.mimeType ?? 'application/octet-stream'),
				name: result.name,
				isVideo: isVideoResult(result),
				sourceWidth: result.width,
				sourceHeight: result.height,
				badge: result.matchedLabels?.length ? result.matchedLabels.join(', ') : null,
				raw: result
			});
			group.count = group.items.length;
		}

		return groups;
	});

	let previewFile = $state<LibraryFile | null>(null);
	let previewOpen = $state(false);
	const previewFiles = $derived<LibraryFile[]>(previewFile ? [previewFile] : []);

	async function openPreview(result: GlobalSearchResult) {
		if (result.kind !== 'file') return;
		try {
			const file = await api.files.get(result.libraryId, result.id);
			previewFile = file;
			previewOpen = true;
		} catch {
			// silent
		}
	}
</script>

<div class="min-h-0 w-full flex-1 space-y-6 overflow-y-auto px-0.5">
	<PageHeader
		title="Search"
		description={activeQuery.length >= MIN_QUERY_LENGTH
			? `Results for “${activeQuery}”`
			: 'Search across all your libraries.'}
	/>

	{#if results.length}
		<div class="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
			<Badge variant="secondary">{searchData.totalCount ?? 0} total matches</Badge>
			<Badge variant="secondary">{results.length} shown</Badge>
			{#if (searchData.totalCount ?? 0) > results.length}
				<span>Showing the top {results.length} most relevant results.</span>
			{/if}
		</div>
	{/if}

	{#if activeQuery.length < MIN_QUERY_LENGTH}
		<div class="flex items-center gap-3 rounded-lg bg-primary/10 px-4 py-3 text-sm text-primary">
			<AppIcon name={ICONS.search} class="size-5 shrink-0" />
			<span>Enter at least {MIN_QUERY_LENGTH} characters to start searching.</span>
		</div>
	{:else if status === 'pending'}
		<div class="flex items-center justify-center py-12">
			<AppIcon name={ICONS.loading} class="size-6 animate-spin text-muted-foreground" />
		</div>
	{:else if status === 'error'}
		<Alert.Root variant="destructive">
			<AppIcon name={ICONS.warning} class="size-4 shrink-0" />
			<Alert.Title>Search failed</Alert.Title>
			<Alert.Description>Try again in a moment.</Alert.Description>
		</Alert.Root>
	{:else if !results.length}
		<EmptyState
			icon={ICONS.search}
			title="No results found"
			description={`Nothing matched “${activeQuery}”. Try a different term.`}
		/>
	{:else}
		<div>
			<JustifiedGallery groups={galleryGroups} onselect={openPreview} />
		</div>
	{/if}

	{#if previewFile}
		<FilePreview
			bind:open={previewOpen}
			file={previewFile}
			libraryId={previewFile.libraryId}
			files={previewFiles}
			onnavigate={(f) => (previewFile = f)}
		/>
	{/if}
</div>
