// frontend/app/components/editor/EditorHeader.vue
<script setup lang="ts">
import { ICONS } from "~/utils/icons";
import type { LibraryFile } from "~~/shared/types/api";
import type { JobStatusButton } from "~/utils/job-status-button";

defineProps<{
  file: LibraryFile | null | undefined;
  transcribing: boolean;
  transcribeButton: JobStatusButton;
  audioDetecting: boolean;
  audioDetectButton: JobStatusButton;
  canDetectAudio: boolean;
  waveformGenerating: boolean;
  waveformButton: JobStatusButton;
}>();

const emit = defineEmits<{
  back: [];
  transcribe: [];
  "audio-detect": [];
  waveform: [];
}>();

function isPlayable(mimeType: string | undefined | null): boolean {
  return !!mimeType && (mimeType.startsWith("video/") || mimeType.startsWith("audio/"));
}
</script>

<template>
  <div class="flex items-center gap-3 w-full">
    <UButton
      color="neutral"
      variant="ghost"
      size="sm"
      :icon="ICONS.back"
      @click="emit('back')"
    >
      Back
    </UButton>
    <div class="min-w-0 flex-1">
      <p class="text-lg font-semibold truncate">{{ file?.name ?? "Loading…" }}</p>
    </div>
    <UButton
      v-if="file && isPlayable(file.mimeType)"
      :color="transcribeButton.color"
      :variant="file?.transcribeStatus === 'failed' ? 'solid' : 'soft'"
      size="sm"
      :icon="ICONS.transcript"
      :loading="transcribeButton.loading || transcribing"
      :disabled="transcribeButton.disabled || transcribing"
      @click="emit('transcribe')"
    >
      {{ transcribeButton.label }}
    </UButton>
    <UButton
      v-if="canDetectAudio"
      :color="audioDetectButton.color"
      :variant="file?.audioDetectStatus === 'failed' ? 'solid' : 'soft'"
      size="sm"
      :icon="ICONS.audioDetect"
      :loading="audioDetectButton.loading || audioDetecting"
      :disabled="audioDetectButton.disabled || audioDetecting"
      @click="emit('audio-detect')"
    >
      {{ audioDetectButton.label }}
    </UButton>
    <UButton
      v-if="file && isPlayable(file.mimeType)"
      :color="waveformButton.color"
      :variant="file?.waveformStatus === 'failed' ? 'solid' : 'soft'"
      size="sm"
      :icon="ICONS.waveform"
      :loading="waveformButton.loading || waveformGenerating"
      :disabled="waveformButton.disabled || waveformGenerating"
      @click="emit('waveform')"
    >
      {{ waveformButton.label }}
    </UButton>
  </div>
</template>

// client/src/lib/components/editor/EditorHeader.svelte
<script lang="ts">
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import { ICONS } from '$lib/utils/icons';
	import type { LibraryFile } from '$lib/types/api';
	import type { JobButtonColor, JobStatusButton } from '$lib/utils/job-status-button';

	type ButtonColor = 'primary' | 'surface' | 'error' | 'warning' | 'success';
	type ButtonVariant = 'filled' | 'tonal';

	interface Props {
		file: LibraryFile | null | undefined;
		transcribing: boolean;
		transcribeButton: JobStatusButton;
		audioDetecting: boolean;
		audioDetectButton: JobStatusButton;
		canDetectAudio: boolean;
		waveformGenerating: boolean;
		waveformButton: JobStatusButton;
		onback?: () => void;
		ontranscribe?: () => void;
		onaudioDetect?: () => void;
		onwaveform?: () => void;
	}

	let {
		file,
		transcribing,
		transcribeButton,
		audioDetecting,
		audioDetectButton,
		canDetectAudio,
		waveformGenerating,
		waveformButton,
		onback,
		ontranscribe,
		onaudioDetect,
		onwaveform
	}: Props = $props();

	function isPlayable(mimeType: string | undefined | null): boolean {
		return !!mimeType && (mimeType.startsWith('video/') || mimeType.startsWith('audio/'));
	}

	// JobButtonColor -> Button color token. `neutral` has no preset of its own;
	// it maps onto the surface palette.
	const colorToken: Record<JobButtonColor, ButtonColor> = {
		primary: 'primary',
		neutral: 'surface',
		warning: 'warning',
		error: 'error'
	};

	// The Vue original used `solid` (filled) for a failed job and `soft` (tonal)
	// otherwise. Mirror that here: filled when failed, tonal otherwise. The Button
	// renders the same `preset-filled-{color}-500` / `preset-tonal-{color}` tokens.
	function actionVariant(failed: boolean): ButtonVariant {
		return failed ? 'filled' : 'tonal';
	}

	const playable = $derived(!!file && isPlayable(file.mimeType));
	const transcribeFailed = $derived(file?.transcribeStatus === 'failed');
	const audioDetectFailed = $derived(file?.audioDetectStatus === 'failed');
	const waveformFailed = $derived(file?.waveformStatus === 'failed');

	const transcribeLoading = $derived(transcribeButton.loading || transcribing);
	const audioDetectLoading = $derived(audioDetectButton.loading || audioDetecting);
	const waveformLoading = $derived(waveformButton.loading || waveformGenerating);
</script>

<div class="flex w-full items-center gap-3">
	<Button variant="tonal" color="surface" size="sm" onclick={() => onback?.()}>
		{#snippet icon()}
			<AppIcon name={ICONS.back} class="size-4" />
		{/snippet}
		Back
	</Button>

	<div class="min-w-0 flex-1">
		<p class="truncate text-lg font-semibold">{file?.name ?? 'Loading…'}</p>
	</div>

	{#if playable}
		<Button
			size="sm"
			variant={actionVariant(transcribeFailed)}
			color={colorToken[transcribeButton.color]}
			loading={transcribeLoading}
			disabled={transcribeButton.disabled || transcribing}
			onclick={() => ontranscribe?.()}
		>
			{#snippet icon()}
				<AppIcon name={ICONS.transcript} class="size-4" />
			{/snippet}
			{transcribeButton.label}
		</Button>
	{/if}

	{#if canDetectAudio}
		<Button
			size="sm"
			variant={actionVariant(audioDetectFailed)}
			color={colorToken[audioDetectButton.color]}
			loading={audioDetectLoading}
			disabled={audioDetectButton.disabled || audioDetecting}
			onclick={() => onaudioDetect?.()}
		>
			{#snippet icon()}
				<AppIcon name={ICONS.audioDetect} class="size-4" />
			{/snippet}
			{audioDetectButton.label}
		</Button>
	{/if}

	{#if playable}
		<Button
			size="sm"
			variant={actionVariant(waveformFailed)}
			color={colorToken[waveformButton.color]}
			loading={waveformLoading}
			disabled={waveformButton.disabled || waveformGenerating}
			onclick={() => onwaveform?.()}
		>
			{#snippet icon()}
				<AppIcon name={ICONS.waveform} class="size-4" />
			{/snippet}
			{waveformButton.label}
		</Button>
	{/if}
</div>
