// frontend/app/components/editor/MomentShareModal.vue
<script setup lang="ts">
import { ICONS } from "~/utils/icons";
import { ref, watch } from "vue";
import { api } from "~/api";
import { useToast } from "~/composables/useToast";
import type { MomentShare } from "~~/shared/types/api";

const props = defineProps<{
  open: boolean;
  libraryId: string;
  fileId: string;
  momentId: string | null;
  sharingEnabled: boolean;
}>();

const emit = defineEmits<{
  "update:open": [value: boolean];
}>();

const toast = useToast();
const shares = ref<MomentShare[]>([]);
const loading = ref(false);
const creating = ref(false);

async function refresh() {
  if (!props.momentId) return;
  loading.value = true;
  try {
    shares.value = await api.moments.listShares(props.libraryId, props.fileId, props.momentId);
  } catch {
    shares.value = [];
  } finally {
    loading.value = false;
  }
}

async function onCreate() {
  if (!props.momentId || !props.sharingEnabled) return;
  creating.value = true;
  try {
    const created = await api.moments.createShare(props.libraryId, props.fileId, props.momentId);
    shares.value = [created, ...shares.value];
    toast.add({ title: "Share link created", color: "success" });
  } catch {
    toast.add({ title: "Failed to create share link", color: "error" });
  } finally {
    creating.value = false;
  }
}

async function onRevoke(token: string) {
  if (!props.momentId) return;
  try {
    await api.moments.revokeShare(props.libraryId, props.fileId, props.momentId, token);
    shares.value = shares.value.filter((s) => s.token !== token);
    toast.add({ title: "Share link revoked", color: "success" });
  } catch {
    toast.add({ title: "Failed to revoke", color: "error" });
  }
}

async function copy(url: string) {
  try {
    await navigator.clipboard.writeText(url);
    toast.add({ title: "Link copied", color: "success" });
  } catch {
    toast.add({ title: "Copy failed", color: "error" });
  }
}

watch(
  () => [props.open, props.momentId],
  ([isOpen]) => {
    if (isOpen) refresh();
  },
);
</script>

<template>
  <UModal
    :open="open"
    title="Share moment"
    :description="
      sharingEnabled
        ? 'Anyone with the link can watch this moment. Revoke to kill access.'
        : 'Sharing is disabled for this library. Turn it on in library settings to create share links.'
    "
    @update:open="emit('update:open', $event)"
  >
    <template #body>
      <div class="space-y-3">
        <UButton
          color="primary"
          :icon="ICONS.link"
          :disabled="!sharingEnabled || creating"
          :loading="creating"
          @click="onCreate"
        >
          Create share link
        </UButton>

        <div v-if="loading" class="text-sm text-muted">Loading…</div>

        <div v-if="shares.length" class="space-y-2">
          <div
            v-for="s in shares"
            :key="s.id"
            class="rounded-md bg-elevated/50 p-3 flex items-center gap-2"
          >
            <code class="text-xs truncate flex-1">{{ s.url }}</code>
            <UButton
              color="neutral"
              variant="ghost"
              size="xs"
              square
              :icon="ICONS.copy"
              aria-label="Copy link"
              @click="copy(s.url)"
            />
            <UButton
              color="error"
              variant="soft"
              size="xs"
              :icon="ICONS.close"
              @click="onRevoke(s.token)"
            >
              Revoke
            </UButton>
          </div>
        </div>
        <div
          v-else-if="!loading"
          class="text-sm text-muted rounded-lg border border-dashed border-default p-4 text-center"
        >
          No active share links.
        </div>
      </div>
    </template>
  </UModal>
</template>

// client/src/lib/components/editor/MomentShareModal.svelte
<script lang="ts">
	import AppModal from '$lib/components/ui/AppModal.svelte';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import { ICONS } from '$lib/utils/icons';
	import { api } from '$lib/api';
	import { toast } from '$lib/state/toast';
	import type { MomentShare } from '$lib/types/api';

	/**
	 * Create / list / revoke public share links for a moment. Two-way bindable
	 * `open`; refreshes the list whenever it opens (or the moment changes).
	 */

	interface Props {
		/** Controlled visibility (two-way bindable). */
		open?: boolean;
		libraryId: string;
		fileId: string;
		momentId: string | null;
		sharingEnabled: boolean;
	}

	let { open = $bindable(false), libraryId, fileId, momentId, sharingEnabled }: Props = $props();

	let shares = $state<MomentShare[]>([]);
	let loading = $state(false);
	let creating = $state(false);

	async function refresh() {
		if (!momentId) return;
		loading = true;
		try {
			shares = await api.moments.listShares(libraryId, fileId, momentId);
		} catch {
			shares = [];
		} finally {
			loading = false;
		}
	}

	async function onCreate() {
		if (!momentId || !sharingEnabled) return;
		creating = true;
		try {
			const created = await api.moments.createShare(libraryId, fileId, momentId);
			shares = [created, ...shares];
			toast.add({ title: 'Share link created', color: 'success' });
		} catch {
			toast.add({ title: 'Failed to create share link', color: 'error' });
		} finally {
			creating = false;
		}
	}

	async function onRevoke(token: string) {
		if (!momentId) return;
		try {
			await api.moments.revokeShare(libraryId, fileId, momentId, token);
			shares = shares.filter((s) => s.token !== token);
			toast.add({ title: 'Share link revoked', color: 'success' });
		} catch {
			toast.add({ title: 'Failed to revoke', color: 'error' });
		}
	}

	async function copy(url: string) {
		try {
			await navigator.clipboard?.writeText(url);
			toast.add({ title: 'Link copied', color: 'success' });
		} catch {
			toast.add({ title: 'Copy failed', color: 'error' });
		}
	}

	// Mirror the Vue `watch([open, momentId])`: refresh whenever it opens.
	$effect(() => {
		// Track both so a moment swap while open re-fetches too.
		void momentId;
		if (open) refresh();
	});

	const description = $derived(
		sharingEnabled
			? 'Anyone with the link can watch this moment. Revoke to kill access.'
			: 'Sharing is disabled for this library. Turn it on in library settings to create share links.'
	);
</script>

<AppModal bind:open title="Share moment" {description}>
	<div class="flex flex-col gap-3">
		<Button
			class="self-start"
			loading={creating}
			disabled={!sharingEnabled || creating}
			onclick={onCreate}
		>
			{#snippet icon()}
				<AppIcon name={ICONS.link} class="size-4" />
			{/snippet}
			<span>Create share link</span>
		</Button>

		{#if loading}
			<div class="text-sm opacity-60">Loading…</div>
		{/if}

		{#if shares.length}
			<div class="flex flex-col gap-2">
				{#each shares as s (s.id)}
					<div class="flex items-center gap-2 rounded-md bg-surface-200-800/50 p-3">
						<code class="flex-1 truncate text-xs">{s.url}</code>
						<button
							type="button"
							class="btn-icon preset-tonal"
							aria-label="Copy link"
							onclick={() => copy(s.url)}
						>
							<AppIcon name={ICONS.copy} class="size-4" />
						</button>
						<Button variant="tonal" color="error" onclick={() => onRevoke(s.token)}>
							{#snippet icon()}
								<AppIcon name={ICONS.close} class="size-4" />
							{/snippet}
							<span>Revoke</span>
						</Button>
					</div>
				{/each}
			</div>
		{:else if !loading}
			<div
				class="rounded-lg border border-dashed border-surface-300-700 p-4 text-center text-sm opacity-60"
			>
				No active share links.
			</div>
		{/if}
	</div>
</AppModal>
