// client/src/lib/components/library/settings/InviteLinkRow.svelte
<script lang="ts">
	import { ICONS } from '$lib/utils/icons';
	import type { LibraryInviteLink } from '$lib/types/api';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import UserAvatar from '$lib/components/ui/UserAvatar.svelte';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import { Button } from '$lib/components/ui/button/index.js';

	interface Props {
		invite: LibraryInviteLink;
		revoking: boolean;
		oncopy?: (inviteUrl: string) => void;
		onrevoke?: (inviteId: string) => void;
	}

	let { invite, revoking, oncopy, onrevoke }: Props = $props();

	let expanded = $state(false);

	const usageLabel = $derived.by(() => {
		const used = invite.useCount;
		const max = invite.maxUses;
		if (max == null) return `${used} ${used === 1 ? 'use' : 'uses'}`;
		return `${used} / ${max} uses`;
	});

	const expiresLabel = $derived.by(() => {
		if (!invite.expiresAt) return 'Never expires';
		const d = new Date(invite.expiresAt);
		return `Expires ${d.toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}`;
	});

	const isExhausted = $derived(invite.maxUses != null && invite.useCount >= invite.maxUses);
	const isExpired = $derived(
		invite.expiresAt != null && new Date(invite.expiresAt).getTime() < Date.now()
	);
	const uses = $derived(invite.uses ?? []);
</script>

<div class="flex flex-col gap-2 px-3 py-3">
	<div class="flex flex-col gap-3 md:flex-row md:items-center">
		<div class="min-w-0 flex-1">
			<p class="truncate text-sm font-medium">{invite.inviteUrl}</p>
			<div class="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
				<span>{usageLabel}</span>
				<span>·</span>
				<span>{expiresLabel}</span>
				{#if isExhausted}
					<Badge variant="outline" class="border-transparent bg-warning/10 text-warning">
						Exhausted
					</Badge>
				{/if}
				{#if isExpired}
					<Badge variant="destructive">Expired</Badge>
				{/if}
			</div>
		</div>
		<div class="flex items-center gap-2">
			{#if uses.length}
				<Button variant="ghost" size="sm" onclick={() => (expanded = !expanded)}>
					<AppIcon name={expanded ? ICONS.chevronUp : ICONS.chevronDown} class="size-4" />
					{uses.length}
				</Button>
			{/if}
			<Button
				variant="ghost"
				size="icon-sm"
				aria-label="Copy invite link"
				onclick={() => oncopy?.(invite.inviteUrl)}
			>
				<AppIcon name={ICONS.copy} class="size-4" />
			</Button>
			<Button
				variant="destructive"
				size="icon-sm"
				aria-label="Revoke invite link"
				disabled={revoking}
				onclick={() => onrevoke?.(invite.id)}
			>
				{#if revoking}
					<AppIcon name={ICONS.loading} class="size-4 animate-spin" />
				{:else}
					<AppIcon name={ICONS.trash} class="size-4" />
				{/if}
			</Button>
		</div>
	</div>
	{#if expanded && uses.length}
		<div class="space-y-2 rounded-md border bg-muted/30 px-3 py-2">
			{#each uses as u, idx (idx)}
				<div class="flex items-center gap-2 text-xs">
					<UserAvatar
						displayName={u.user.displayName}
						avatarUrl={u.user.avatarUrl}
						sizeClass="w-6"
					/>
					<div class="min-w-0 flex-1">
						<p class="truncate">{u.user.displayName}</p>
						<p class="truncate text-muted-foreground">{u.user.email}</p>
					</div>
					<span class="text-muted-foreground">{new Date(u.usedAt).toLocaleString()}</span>
				</div>
			{/each}
		</div>
	{/if}
</div>

// frontend/app/components/library/settings/InviteLinkRow.vue
<script setup lang="ts">
import type { LibraryInviteLink } from "~~/shared/types/api";
import UserAvatar from "~/components/UserAvatar.vue";

interface Props {
  invite: LibraryInviteLink;
  revoking: boolean;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  copy: [inviteUrl: string];
  revoke: [inviteId: string];
}>();

const expanded = ref(false);

const usageLabel = computed(() => {
  const used = props.invite.useCount;
  const max = props.invite.maxUses;
  if (max == null) return `${used} ${used === 1 ? "use" : "uses"}`;
  return `${used} / ${max} uses`;
});

const expiresLabel = computed(() => {
  if (!props.invite.expiresAt) return "Never expires";
  const d = new Date(props.invite.expiresAt);
  return `Expires ${d.toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}`;
});

const isExhausted = computed(
  () => props.invite.maxUses != null && props.invite.useCount >= props.invite.maxUses,
);
const isExpired = computed(
  () => props.invite.expiresAt != null && new Date(props.invite.expiresAt).getTime() < Date.now(),
);
const uses = computed(() => props.invite.uses ?? []);
</script>

<template>
  <div class="px-3 py-3 flex flex-col gap-2">
    <div class="flex flex-col md:flex-row md:items-center gap-3">
      <div class="flex-1 min-w-0">
        <p class="text-sm font-medium truncate">{{ invite.inviteUrl }}</p>
        <div class="flex flex-wrap items-center gap-2 text-xs text-muted">
          <span>{{ usageLabel }}</span>
          <span>·</span>
          <span>{{ expiresLabel }}</span>
          <UBadge v-if="isExhausted" color="warning" variant="subtle" size="xs">Exhausted</UBadge>
          <UBadge v-if="isExpired" color="error" variant="subtle" size="xs">Expired</UBadge>
        </div>
      </div>
      <div class="flex items-center gap-2">
        <UButton
          v-if="uses.length"
          color="neutral"
          variant="ghost"
          size="sm"
          :icon="expanded ? 'i-lucide-chevron-up' : 'i-lucide-chevron-down'"
          @click="expanded = !expanded"
        >
          {{ uses.length }}
        </UButton>
        <UButton
          color="neutral"
          variant="soft"
          size="sm"
          icon="i-lucide-copy"
          square
          @click="emit('copy', invite.inviteUrl)"
        />
        <UButton
          color="error"
          variant="soft"
          size="sm"
          icon="i-lucide-trash-2"
          square
          :loading="revoking"
          :disabled="revoking"
          @click="emit('revoke', invite.id)"
        />
      </div>
    </div>
    <div
      v-if="expanded && uses.length"
      class="rounded-md border border-default bg-elevated/30 px-3 py-2 space-y-2"
    >
      <div v-for="(u, idx) in uses" :key="idx" class="flex items-center gap-2 text-xs">
        <UserAvatar
          :display-name="u.user.displayName"
          :avatar-url="u.user.avatarUrl"
          size-class="w-6"
        />
        <div class="min-w-0 flex-1">
          <p class="truncate">{{ u.user.displayName }}</p>
          <p class="text-muted truncate">{{ u.user.email }}</p>
        </div>
        <span class="text-muted">{{ new Date(u.usedAt).toLocaleString() }}</span>
      </div>
    </div>
  </div>
</template>
