// frontend/app/components/LibraryBreadcrumb.vue
<script setup lang="ts">
import type { BreadcrumbItem } from "@nuxt/ui";
import { useLibraryFolderPath } from "~/composables/useLibraryFolderPath";

/**
 * The library page's primary heading: a breadcrumb whose root is the library
 * name (links to the Files root) and whose tail is the current folder ancestry
 * (only present on the Files tab, via `useLibraryFolderPath`). No leading home
 * icon — the library name is the anchor. The current crumb is rendered by
 * `UBreadcrumb` as the non-link "current page" and styled as the heading.
 */
const props = defineProps<{
  libraryId: string;
  libraryName?: string;
}>();

const folderPath = useLibraryFolderPath();

const items = computed<BreadcrumbItem[]>(() => {
  const base = `/libraries/${props.libraryId}`;
  const crumbs: BreadcrumbItem[] = [
    { label: props.libraryName || "Library", to: base },
    ...folderPath.value.map((crumb) => ({
      label: crumb.name,
      to: `${base}?folder=${encodeURIComponent(crumb.id)}`,
    })),
  ];
  // Emphasise the current (last) crumb so the breadcrumb reads as the heading.
  const lastIndex = crumbs.length - 1;
  return crumbs.map((item, index) =>
    index === lastIndex ? { ...item, class: "text-highlighted font-semibold" } : item,
  );
});
</script>

<template>
  <UBreadcrumb
    :items="items"
    :ui="{
      root: 'min-w-0',
      list: 'flex-nowrap',
      item: 'min-w-0',
      link: 'min-w-0 text-lg sm:text-xl font-medium',
      linkLabel: 'truncate max-w-[7rem] sm:max-w-xs',
      separator: 'mx-1 sm:mx-1.5',
      separatorIcon: 'size-4 sm:size-5',
    }"
  />
</template>

// client/src/lib/components/LibraryBreadcrumb.svelte
<script lang="ts">
	import * as Breadcrumb from '$lib/components/ui/breadcrumb/index.js';
	import { libraryFolderPath } from '$lib/state/library-folder-path.svelte';

	/**
	 * The library page's primary heading: a breadcrumb whose root is the library
	 * name (links to the Files root) and whose tail is the current folder ancestry
	 * (only present on the Files tab, via the `libraryFolderPath` store). No leading
	 * home icon — the library name is the anchor. The current (last) crumb is the
	 * non-link "current page" and is styled as the heading.
	 */
	interface Props {
		libraryId: string;
		libraryName?: string;
	}

	interface Crumb {
		label: string;
		to: string;
	}

	let { libraryId, libraryName }: Props = $props();

	const crumbs = $derived.by<Crumb[]>(() => {
		const base = `/libraries/${libraryId}`;
		return [
			{ label: libraryName || 'Library', to: base },
			...libraryFolderPath.value.map((crumb) => ({
				label: crumb.name,
				to: `${base}?folder=${encodeURIComponent(crumb.id)}`
			}))
		];
	});

	const lastIndex = $derived(crumbs.length - 1);
</script>

<Breadcrumb.Root aria-label="Breadcrumb" class="min-w-0">
	<Breadcrumb.List class="flex-nowrap gap-0 sm:gap-0">
		{#each crumbs as crumb, index (crumb.to)}
			{#if index > 0}
				<Breadcrumb.Separator class="mx-1 shrink-0 sm:mx-1.5" />
			{/if}
			<Breadcrumb.Item class="min-w-0">
				{#if index === lastIndex}
					<Breadcrumb.Page
						class="block truncate text-lg font-semibold text-foreground sm:max-w-xs sm:text-xl"
					>
						{crumb.label}
					</Breadcrumb.Page>
				{:else}
					<Breadcrumb.Link
						href={crumb.to}
						class="block truncate text-lg font-medium text-muted-foreground sm:max-w-xs sm:text-xl"
					>
						{crumb.label}
					</Breadcrumb.Link>
				{/if}
			</Breadcrumb.Item>
		{/each}
	</Breadcrumb.List>
</Breadcrumb.Root>
