// frontend/app/components/UploadProgress.vue
<script setup lang="ts">
import { ICONS } from "~/utils/icons";
import { formatFileSize } from "~/utils/mime-icons";
import { useUploadQueue } from "~/composables/useUploadQueue";
import AppIcon from "~/components/AppIcon.vue";

const {
  activeUploads,
  hasActiveUploads,
  erroredUploads,
  uploadSpeed,
  retryFile,
  retryAll,
  removeFile,
  clearErrors,
} = useUploadQueue();
const expanded = ref(true);
</script>

<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition duration-200 ease-out"
      enter-from-class="translate-y-4 opacity-0"
      enter-to-class="translate-y-0 opacity-100"
      leave-active-class="transition duration-150 ease-in"
      leave-from-class="translate-y-0 opacity-100"
      leave-to-class="translate-y-4 opacity-0"
    >
      <div
        v-if="hasActiveUploads"
        class="fixed bottom-4 right-4 z-50 w-96 bg-default rounded-xl shadow-lg border border-default overflow-hidden"
      >
        <div
          class="flex items-center justify-between px-4 py-2.5 cursor-pointer select-none bg-elevated"
          @click="expanded = !expanded"
        >
          <span class="text-sm font-medium">
            Uploading {{ activeUploads.length }}
            {{ activeUploads.length === 1 ? "file" : "files" }}
          </span>
          <div class="flex items-center gap-2">
            <span v-if="uploadSpeed > 0" class="text-xs text-muted">
              {{ formatFileSize(uploadSpeed) }}/s
            </span>
            <AppIcon
              :name="expanded ? ICONS.chevronDown : ICONS.chevronUp"
              class="size-4 text-muted"
            />
          </div>
        </div>

        <div
          v-if="expanded && erroredUploads.length > 0"
          class="flex items-center justify-between px-4 py-1.5 border-t border-default"
        >
          <span class="text-xs text-error">{{ erroredUploads.length }} failed</span>
          <div class="flex gap-1">
            <UButton color="neutral" variant="ghost" size="xs" @click="retryAll">
              Retry All
            </UButton>
            <UButton color="error" variant="ghost" size="xs" @click="clearErrors">Clear</UButton>
          </div>
        </div>

        <div v-if="expanded" class="max-h-64 overflow-y-auto px-2 py-2 space-y-1">
          <div
            v-for="item in activeUploads"
            :key="item.id"
            class="px-2 py-2 rounded-lg bg-elevated/60"
          >
            <div class="flex items-center justify-between mb-1">
              <span class="text-sm truncate flex-1 mr-2">{{ item.file.name }}</span>
              <span class="text-xs text-muted whitespace-nowrap">{{ item.libraryName }}</span>
            </div>

            <div v-if="item.status === 'uploading'" class="flex items-center gap-2">
              <UProgress
                class="flex-1"
                :model-value="item.progress"
                :max="100"
                color="primary"
                size="sm"
              />
              <span class="text-xs text-muted w-8 text-right">{{ item.progress }}%</span>
            </div>

            <div v-else-if="item.status === 'error'" class="flex items-center justify-between">
              <span class="text-xs text-error">{{ item.error }}</span>
              <div class="flex gap-1">
                <UButton color="neutral" variant="ghost" size="xs" @click="retryFile(item.id)">
                  Retry
                </UButton>
                <UButton color="error" variant="ghost" size="xs" @click="removeFile(item.id)">
                  Remove
                </UButton>
              </div>
            </div>

            <div v-else-if="item.status === 'done'" class="flex items-center gap-1">
              <AppIcon :name="ICONS.check" class="size-4 text-success" />
              <span class="text-xs text-success">Complete</span>
            </div>

            <div v-else class="text-xs text-muted">Waiting...</div>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

// client/src/lib/components/UploadProgress.svelte
<script lang="ts">
	import { ICONS } from '$lib/utils/icons';
	import { formatFileSize } from '$lib/utils/mime-icons';
	import { uploadQueue } from '$lib/state/upload-queue.svelte';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import Button from '$lib/components/ui/Button.svelte';

	let expanded = $state(true);
</script>

{#if uploadQueue.hasActiveUploads}
	<div
		class="fixed right-4 bottom-4 z-50 w-96 overflow-hidden rounded-xl border border-surface-300-700 bg-surface-50-950 shadow-xl"
	>
		<button
			type="button"
			class="flex w-full items-center justify-between bg-surface-100-900 px-4 py-2.5 text-left select-none"
			onclick={() => (expanded = !expanded)}
		>
			<span class="text-sm font-medium">
				Uploading {uploadQueue.activeUploads.length}
				{uploadQueue.activeUploads.length === 1 ? 'file' : 'files'}
			</span>
			<div class="flex items-center gap-2">
				{#if uploadQueue.uploadSpeed > 0}
					<span class="text-xs opacity-60">{formatFileSize(uploadQueue.uploadSpeed)}/s</span>
				{/if}
				<AppIcon name={expanded ? ICONS.chevronDown : ICONS.chevronUp} class="size-4 opacity-60" />
			</div>
		</button>

		{#if expanded && uploadQueue.erroredUploads.length > 0}
			<div class="flex items-center justify-between border-t border-surface-300-700 px-4 py-1.5">
				<span class="text-xs text-error-500">{uploadQueue.erroredUploads.length} failed</span>
				<div class="flex gap-1">
					<button
						type="button"
						class="btn preset-tonal btn-sm"
						onclick={() => uploadQueue.retryAll()}
					>
						Retry All
					</button>
					<Button variant="tonal" color="error" size="sm" onclick={() => uploadQueue.clearErrors()}>
						Clear
					</Button>
				</div>
			</div>
		{/if}

		{#if expanded}
			<div class="max-h-64 space-y-1 overflow-y-auto px-2 py-2">
				{#each uploadQueue.activeUploads as item (item.id)}
					<div class="rounded-lg bg-surface-100-900/60 px-2 py-2">
						<div class="mb-1 flex items-center justify-between">
							<span class="mr-2 flex-1 truncate text-sm">{item.file.name}</span>
							<span class="text-xs whitespace-nowrap opacity-60">{item.libraryName}</span>
						</div>

						{#if item.status === 'uploading'}
							<div class="flex items-center gap-2">
								<div
									class="h-1.5 flex-1 overflow-hidden rounded-full bg-surface-300-700"
									role="progressbar"
									aria-valuenow={item.progress}
									aria-valuemin={0}
									aria-valuemax={100}
								>
									<div
										class="h-full rounded-full bg-primary-500 transition-[width] duration-150"
										style:width="{item.progress}%"
									></div>
								</div>
								<span class="w-8 text-right text-xs opacity-60">{item.progress}%</span>
							</div>
						{:else if item.status === 'error'}
							<div class="flex items-center justify-between">
								<span class="text-xs text-error-500">{item.error}</span>
								<div class="flex gap-1">
									<button
										type="button"
										class="btn preset-tonal btn-sm"
										onclick={() => uploadQueue.retryFile(item.id)}
									>
										Retry
									</button>
									<Button
										variant="tonal"
										color="error"
										size="sm"
										onclick={() => uploadQueue.removeFile(item.id)}
									>
										Remove
									</Button>
								</div>
							</div>
						{:else if item.status === 'done'}
							<div class="flex items-center gap-1">
								<AppIcon name={ICONS.check} class="size-4 text-success-500" />
								<span class="text-xs text-success-500">Complete</span>
							</div>
						{:else}
							<div class="text-xs opacity-60">Waiting...</div>
						{/if}
					</div>
				{/each}
			</div>
		{/if}
	</div>
{/if}
