// frontend/app/components/UploadModal.vue
<script setup lang="ts">
import { ICONS } from "~/utils/icons";
import { useUploadQueue } from "~/composables/useUploadQueue";
import AppModal from "~/components/AppModal.vue";

const props = defineProps<{
  libraryId: string;
  libraryName: string;
  parentFolderId: string | null;
}>();

const open = defineModel<boolean>("open", { default: false });

const { addFiles } = useUploadQueue();
const selectedFiles = ref<File[]>([]);
const selectedFileCount = computed(() => selectedFiles.value.length);

function handleUpload() {
  if (!selectedFileCount.value) return;
  addFiles(selectedFiles.value, props.libraryId, props.libraryName, props.parentFolderId);
  selectedFiles.value = [];
  open.value = false;
}

function handleClose() {
  selectedFiles.value = [];
}

function onFileChange(event: Event) {
  const target = event.target as HTMLInputElement;
  if (target.files) {
    selectedFiles.value = Array.from(target.files);
  }
}

watch(open, (val) => {
  if (!val) handleClose();
});
</script>

<template>
  <AppModal v-model:open="open">
    <h3 class="text-lg font-bold">Upload Files</h3>

    <div class="py-4">
      <p class="text-sm text-muted mb-3">
        Uploading to <strong>{{ libraryName }}</strong>
      </p>

      <input
        type="file"
        class="block w-full text-sm text-default file:mr-3 file:rounded-md file:border-0 file:bg-elevated file:px-3 file:py-2 file:text-sm file:font-medium file:text-default hover:file:bg-accented/70 cursor-pointer"
        multiple
        @change="onFileChange"
      />

      <p v-if="selectedFileCount" class="mt-3 text-sm text-muted">
        {{ selectedFileCount }} file{{ selectedFileCount === 1 ? "" : "s" }} selected
      </p>
    </div>

    <div class="flex justify-end gap-2">
      <UButton color="neutral" variant="soft" size="sm" @click="open = false">Cancel</UButton>
      <UButton
        color="primary"
        variant="soft"
        size="sm"
        :icon="ICONS.upload"
        :disabled="!selectedFileCount"
        @click="handleUpload"
      >
        Upload
      </UButton>
    </div>
  </AppModal>
</template>

// client/src/lib/components/UploadModal.svelte
<script lang="ts">
	import AppModal from '$lib/components/ui/AppModal.svelte';
	import AppIcon from '$lib/components/ui/AppIcon.svelte';
	import { ICONS } from '$lib/utils/icons';
	import { uploadQueue } from '$lib/state/upload-queue.svelte';

	/**
	 * Upload dialog. Picks files via a native multi-file input and queues them
	 * onto the global TUS upload queue, then closes. Ported from the Nuxt
	 * `UploadModal.vue` — two-way bindable `open`, clears its selection whenever
	 * the modal closes.
	 */

	interface Props {
		libraryId: string;
		libraryName: string;
		parentFolderId: string | null;
		/** Controlled visibility (two-way bindable). */
		open?: boolean;
	}

	let { libraryId, libraryName, parentFolderId, open = $bindable(false) }: Props = $props();

	let selectedFiles = $state<File[]>([]);
	const selectedFileCount = $derived(selectedFiles.length);

	function handleUpload() {
		if (!selectedFileCount) return;
		uploadQueue.addFiles(selectedFiles, libraryId, libraryName, parentFolderId);
		selectedFiles = [];
		open = false;
	}

	function onFileChange(event: Event) {
		const target = event.target as HTMLInputElement;
		if (target.files) {
			selectedFiles = Array.from(target.files);
		}
	}

	// Mirror the Vue `watch(open)`: clear the selection whenever the modal closes.
	$effect(() => {
		if (!open) selectedFiles = [];
	});
</script>

<AppModal bind:open title="Upload Files">
	<div class="flex flex-col gap-3">
		<p class="text-sm opacity-75">
			Uploading to <strong>{libraryName}</strong>
		</p>

		<input
			type="file"
			class="block w-full cursor-pointer text-sm file:mr-3 file:rounded-md file:border-0 file:bg-surface-200-800 file:px-3 file:py-2 file:text-sm file:font-medium hover:file:bg-surface-300-700"
			multiple
			onchange={onFileChange}
		/>

		{#if selectedFileCount}
			<p class="text-sm opacity-75">
				{selectedFileCount} file{selectedFileCount === 1 ? '' : 's'} selected
			</p>
		{/if}
	</div>

	<div class="flex justify-end gap-2">
		<button type="button" class="btn preset-tonal" onclick={() => (open = false)}>Cancel</button>
		<button
			type="button"
			class="btn preset-filled-primary-500"
			disabled={!selectedFileCount}
			onclick={handleUpload}
		>
			<AppIcon name={ICONS.upload} class="size-4" />
			<span>Upload</span>
		</button>
	</div>
</AppModal>
